// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type MiskoLaboratory struct {
	Singleton bool
	Name      string
	Code      *string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MiskoUser struct {
	ID             string
	Email          string
	Name           string
	Role           string
	PasswordHash   string
	SessionVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
