// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const createLaboratory = `-- name: CreateLaboratory :execrows
INSERT INTO misko.laboratory (name, code, timezone)
VALUES ($1, $2, $3)
ON CONFLICT (singleton) DO NOTHING
`

type CreateLaboratoryParams struct {
	Name     string
	Code     *string
	Timezone string
}

func (q *Queries) CreateLaboratory(ctx context.Context, arg CreateLaboratoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, createLaboratory, arg.Name, arg.Code, arg.Timezone)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLaboratory = `-- name: GetLaboratory :one
SELECT name, code, timezone, created_at, updated_at
FROM misko.laboratory
WHERE singleton
`

type GetLaboratoryRow struct {
	Name      string
	Code      *string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetLaboratory(ctx context.Context) (GetLaboratoryRow, error) {
	row := q.db.QueryRow(ctx, getLaboratory)
	var i GetLaboratoryRow
	err := row.Scan(
		&i.Name,
		&i.Code,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLaboratory = `-- name: UpdateLaboratory :one
UPDATE misko.laboratory
SET name = coalesce($1, name),
    code = CASE WHEN $2::boolean THEN $3 ELSE code END,
    timezone = coalesce($4, timezone),
    updated_at = now()
WHERE singleton
RETURNING name, code, timezone, created_at, updated_at
`

type UpdateLaboratoryParams struct {
	Name     *string
	SetCode  bool
	Code     *string
	Timezone *string
}

type UpdateLaboratoryRow struct {
	Name      string
	Code      *string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// set_code distinguishes "leave code unchanged" from "clear code".
func (q *Queries) UpdateLaboratory(ctx context.Context, arg UpdateLaboratoryParams) (UpdateLaboratoryRow, error) {
	row := q.db.QueryRow(ctx, updateLaboratory,
		arg.Name,
		arg.SetCode,
		arg.Code,
		arg.Timezone,
	)
	var i UpdateLaboratoryRow
	err := row.Scan(
		&i.Name,
		&i.Code,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
