// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const createCalibration = `-- name: CreateCalibration :one
INSERT INTO misko.calibrations (recording_id, supersedes_id, camera_id, frame_width, frame_height, crop_x, crop_y, crop_width, crop_height,
    reference_frame_us, measurement_plane, fit_points, check_points, transform, fit_rms_error_cm, check_rms_error_cm, check_max_error_cm,
    tolerance_cm, algorithm_version, status, rejection_reason, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22)
RETURNING id, recording_id, supersedes_id, camera_id, frame_width, frame_height, crop_x, crop_y, crop_width, crop_height, reference_frame_us, measurement_plane, fit_points, check_points, transform, fit_rms_error_cm, check_rms_error_cm, check_max_error_cm, tolerance_cm, algorithm_version, status, rejection_reason, created_by, created_at
`

type CreateCalibrationParams struct {
	RecordingID      string
	SupersedesID     *string
	CameraID         string
	FrameWidth       int32
	FrameHeight      int32
	CropX            int32
	CropY            int32
	CropWidth        int32
	CropHeight       int32
	ReferenceFrameUs int64
	MeasurementPlane string
	FitPoints        []byte
	CheckPoints      []byte
	Transform        []float64
	FitRmsErrorCm    float64
	CheckRmsErrorCm  float64
	CheckMaxErrorCm  float64
	ToleranceCm      float64
	AlgorithmVersion string
	Status           string
	RejectionReason  *string
	CreatedBy        string
}

func (q *Queries) CreateCalibration(ctx context.Context, arg CreateCalibrationParams) (MiskoCalibration, error) {
	row := q.db.QueryRow(ctx, createCalibration,
		arg.RecordingID,
		arg.SupersedesID,
		arg.CameraID,
		arg.FrameWidth,
		arg.FrameHeight,
		arg.CropX,
		arg.CropY,
		arg.CropWidth,
		arg.CropHeight,
		arg.ReferenceFrameUs,
		arg.MeasurementPlane,
		arg.FitPoints,
		arg.CheckPoints,
		arg.Transform,
		arg.FitRmsErrorCm,
		arg.CheckRmsErrorCm,
		arg.CheckMaxErrorCm,
		arg.ToleranceCm,
		arg.AlgorithmVersion,
		arg.Status,
		arg.RejectionReason,
		arg.CreatedBy,
	)
	var i MiskoCalibration
	err := row.Scan(
		&i.ID,
		&i.RecordingID,
		&i.SupersedesID,
		&i.CameraID,
		&i.FrameWidth,
		&i.FrameHeight,
		&i.CropX,
		&i.CropY,
		&i.CropWidth,
		&i.CropHeight,
		&i.ReferenceFrameUs,
		&i.MeasurementPlane,
		&i.FitPoints,
		&i.CheckPoints,
		&i.Transform,
		&i.FitRmsErrorCm,
		&i.CheckRmsErrorCm,
		&i.CheckMaxErrorCm,
		&i.ToleranceCm,
		&i.AlgorithmVersion,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordingRef = `-- name: GetRecordingRef :one
SELECT r.id, r.test_id, a.status AS video_status, t.paradigm_key, t.paradigm_version, e.apparatus
FROM misko.test_recordings r
JOIN misko.video_assets a ON a.id = r.video_asset_id
JOIN misko.tests t ON t.id = r.test_id
JOIN misko.environment_revisions e ON e.id = t.environment_revision_id
WHERE r.test_id = $1 AND r.id = $2
`

type GetRecordingRefParams struct {
	TestID string
	ID     string
}

type GetRecordingRefRow struct {
	ID              string
	TestID          string
	VideoStatus     string
	ParadigmKey     string
	ParadigmVersion int32
	Apparatus       []byte
}

func (q *Queries) GetRecordingRef(ctx context.Context, arg GetRecordingRefParams) (GetRecordingRefRow, error) {
	row := q.db.QueryRow(ctx, getRecordingRef, arg.TestID, arg.ID)
	var i GetRecordingRefRow
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.VideoStatus,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.Apparatus,
	)
	return i, err
}

const listCalibrations = `-- name: ListCalibrations :many
SELECT id, recording_id, supersedes_id, camera_id, frame_width, frame_height, crop_x, crop_y, crop_width, crop_height, reference_frame_us, measurement_plane, fit_points, check_points, transform, fit_rms_error_cm, check_rms_error_cm, check_max_error_cm, tolerance_cm, algorithm_version, status, rejection_reason, created_by, created_at FROM misko.calibrations WHERE recording_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCalibrations(ctx context.Context, recordingID string) ([]MiskoCalibration, error) {
	rows, err := q.db.Query(ctx, listCalibrations, recordingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoCalibration
	for rows.Next() {
		var i MiskoCalibration
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.SupersedesID,
			&i.CameraID,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.CropX,
			&i.CropY,
			&i.CropWidth,
			&i.CropHeight,
			&i.ReferenceFrameUs,
			&i.MeasurementPlane,
			&i.FitPoints,
			&i.CheckPoints,
			&i.Transform,
			&i.FitRmsErrorCm,
			&i.CheckRmsErrorCm,
			&i.CheckMaxErrorCm,
			&i.ToleranceCm,
			&i.AlgorithmVersion,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecordingRef = `-- name: LockRecordingRef :one
SELECT r.id, r.test_id, a.status AS video_status, t.paradigm_key, t.paradigm_version, e.apparatus
FROM misko.test_recordings r
JOIN misko.video_assets a ON a.id = r.video_asset_id
JOIN misko.tests t ON t.id = r.test_id
JOIN misko.environment_revisions e ON e.id = t.environment_revision_id
WHERE r.test_id = $1 AND r.id = $2
FOR UPDATE OF r
`

type LockRecordingRefParams struct {
	TestID string
	ID     string
}

type LockRecordingRefRow struct {
	ID              string
	TestID          string
	VideoStatus     string
	ParadigmKey     string
	ParadigmVersion int32
	Apparatus       []byte
}

// The row lock serializes calibrations of one recording; recordings are never updated.
func (q *Queries) LockRecordingRef(ctx context.Context, arg LockRecordingRefParams) (LockRecordingRefRow, error) {
	row := q.db.QueryRow(ctx, lockRecordingRef, arg.TestID, arg.ID)
	var i LockRecordingRefRow
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.VideoStatus,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.Apparatus,
	)
	return i, err
}
