// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MiskoAdministration struct {
	ID                  string
	ExperimentID        string
	EnrollmentID        string
	SubjectID           string
	SubstanceID         string
	SubstanceName       string
	PlanID              pgtype.UUID
	WeightMeasurementID pgtype.UUID
	BodyMilligrams      *int64
	AmountMicro         int64
	Unit                string
	Route               string
	AdministeredAt      time.Time
	Notes               *string
	RecordedBy          string
	CreatedAt           time.Time
}

type MiskoAnalysisArtifact struct {
	RunID        string
	Attempt      int32
	ObjectName   string
	Kind         string
	Bucket       string
	Generation   int64
	SizeBytes    int64
	Crc32c       int64
	ContentType  string
	VideoAssetID pgtype.UUID
}

type MiskoAnalysisEvent struct {
	ID         string
	RunID      string
	Attempt    int32
	TestID     string
	EventType  string
	Kind       string
	StartUs    int64
	EndUs      int64
	Confidence float32
	TrialID    pgtype.UUID
}

type MiskoAnalysisOutputUpload struct {
	RunID       string
	Attempt     int32
	ObjectName  string
	Kind        string
	ContentType string
	SizeBytes   int64
	Crc32c      int64
	CreatedAt   time.Time
}

type MiskoAnalysisRun struct {
	ID                    string
	ExperimentID          string
	TestID                string
	RecordingID           string
	SourceAssetID         string
	SourceGeneration      int64
	SourceCrc32c          int64
	ClipStartUs           int64
	ClipEndUs             *int64
	CalibrationID         pgtype.UUID
	ParadigmKey           string
	ParadigmVersion       int32
	MetricEngineVersion   int32
	ResultSchemaVersion   int32
	EnvironmentRevisionID string
	ProtocolVersionID     string
	Parameters            []byte
	Trigger               string
	Status                string
	Attempt               int32
	MaxAttempts           int32
	WorkerID              pgtype.UUID
	LeaseExpiresAt        *time.Time
	AvailableAt           time.Time
	ModelVersion          *string
	FailureReason         *string
	CreatedBy             pgtype.UUID
	CreatedAt             time.Time
	FinishedAt            *time.Time
}

type MiskoAnalysisVideoPair struct {
	RunID              string
	Attempt            int32
	SourceAssetID      string
	SourceGeneration   int64
	AnalyzedAssetID    string
	SourceOffsetUs     int64
	OutputOffsetUs     int64
	TimeMappingVersion string
}

type MiskoAnalysisWorker struct {
	ID           string
	Name         string
	ModelVersion string
	TokenSha256  []byte
	DisabledAt   *time.Time
	CreatedBy    string
	CreatedAt    time.Time
}

type MiskoCalibration struct {
	ID               string
	RecordingID      string
	SupersedesID     pgtype.UUID
	CameraID         string
	FrameWidth       int32
	FrameHeight      int32
	CropX            int32
	CropY            int32
	CropWidth        int32
	CropHeight       int32
	ReferenceFrameUs int64
	MeasurementPlane string
	FitPoints        []byte
	CheckPoints      []byte
	Transform        []float64
	FitRmsErrorCm    float64
	CheckRmsErrorCm  float64
	CheckMaxErrorCm  float64
	ToleranceCm      float64
	AlgorithmVersion string
	Status           string
	RejectionReason  *string
	CreatedBy        string
	CreatedAt        time.Time
}

type MiskoDiseaseModel struct {
	ID          string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MiskoEnrollment struct {
	ID           string
	ExperimentID string
	SubjectID    string
	EnrolledAt   time.Time
	CreatedAt    time.Time
}

type MiskoEnvironment struct {
	ID          string
	Name        string
	ParadigmKey string
	Notes       *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MiskoEnvironmentRevision struct {
	ID              string
	EnvironmentID   string
	ParadigmKey     string
	Number          int32
	ParadigmVersion int32
	Apparatus       []byte
	Notes           *string
	CreatedBy       string
	CreatedAt       time.Time
}

type MiskoExperiment struct {
	ID              string
	Code            string
	Title           string
	Description     *string
	RequiresControl bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MiskoExperimentGroup struct {
	ID           string
	ExperimentID string
	Name         string
	Role         string
	TargetSize   *int32
	Description  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoExperimentPhase struct {
	ID           string
	ExperimentID string
	Name         string
	Position     int32
	Description  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoGroupAssignment struct {
	ID           string
	ExperimentID string
	EnrollmentID string
	GroupID      string
	ValidFrom    time.Time
	ValidTo      *time.Time
	CreatedAt    time.Time
}

type MiskoInterventionPlan struct {
	ID           string
	ExperimentID string
	GroupID      string
	PhaseID      pgtype.UUID
	SubstanceID  string
	AmountMicro  int64
	Unit         string
	Route        string
	Schedule     string
	Notes        *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoLaboratory struct {
	Singleton bool
	Name      string
	Code      *string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MiskoMetricResult struct {
	RunID         string
	Attempt       int32
	MetricKey     string
	Unit          string
	Value         *float64
	MissingReason *string
}

type MiskoProtocol struct {
	ID           string
	ExperimentID string
	Name         string
	Description  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoProtocolStep struct {
	ProtocolVersionID     string
	Position              int32
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	TrialType             string
	Trials                int32
	InterTrialIntervalS   int32
	Session               []byte
	Notes                 *string
}

type MiskoProtocolVersion struct {
	ID           string
	ExperimentID string
	ProtocolID   string
	Number       int32
	StepCount    int32
	Notes        *string
	CreatedBy    string
	CreatedAt    time.Time
}

type MiskoReportRun struct {
	ID                  string
	ExperimentID        string
	TestID              string
	RecordingID         string
	SourceAssetID       string
	CalibrationID       pgtype.UUID
	ParadigmKey         string
	ParadigmVersion     int32
	MetricEngineVersion int32
	ResultSchemaVersion int32
	Trigger             string
	ModelVersion        *string
	FinishedAt          *time.Time
	Latest              bool
}

type MiskoReportTest struct {
	TestID                string
	ExperimentID          string
	ExperimentCode        string
	SubjectID             string
	SubjectCode           string
	Species               string
	Sex                   string
	PhaseID               pgtype.UUID
	PhaseName             *string
	GroupID               pgtype.UUID
	GroupName             *string
	GroupRole             *string
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	EnvironmentID         string
	EnvironmentName       string
	EnvironmentRevision   int32
	TestStatus            string
	ScheduledAt           time.Time
	TrialCount            int64
}

type MiskoSubject struct {
	ID        string
	Code      string
	Species   string
	Sex       string
	Strain    *string
	BirthDate pgtype.Date
	Notes     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MiskoSubjectCondition struct {
	ID               string
	SubjectID        string
	DiseaseModelID   string
	DiseaseModelName string
	EnrollmentID     pgtype.UUID
	Status           string
	ObservedAt       time.Time
	Notes            *string
	RecordedBy       string
	CreatedAt        time.Time
}

type MiskoSubstance struct {
	ID          string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MiskoTest struct {
	ID                    string
	ExperimentID          string
	EnrollmentID          string
	SubjectID             string
	PhaseID               pgtype.UUID
	GroupID               pgtype.UUID
	ProtocolVersionID     string
	StepPosition          int32
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	PlannedTrials         int32
	Status                string
	ScheduledAt           time.Time
	StartedAt             *time.Time
	CompletedAt           *time.Time
	CancelledAt           *time.Time
	CancelReason          *string
	Notes                 *string
	CreatedBy             string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type MiskoTestComment struct {
	ID        string
	TestID    string
	AuthorID  string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MiskoTestRecording struct {
	ID           string
	ExperimentID string
	TestID       string
	VideoAssetID string
	ClipStartUs  int64
	ClipEndUs    *int64
	CreatedBy    string
	CreatedAt    time.Time
}

type MiskoTrial struct {
	ID         string
	TestID     string
	Number     int32
	Repetition int32
	Attempt    int32
	StartedAt  time.Time
	EndedAt    *time.Time
	Notes      *string
	RecordedBy string
	CreatedAt  time.Time
}

type MiskoUser struct {
	ID             string
	Email          string
	Name           string
	Role           string
	PasswordHash   string
	SessionVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MiskoVideoAsset struct {
	ID              string
	Kind            string
	Bucket          string
	ObjectName      string
	ContentType     string
	FileName        *string
	SizeBytes       int64
	Crc32c          int64
	Status          string
	Generation      *int64
	RejectionReason *string
	VerifiedAt      *time.Time
	CreatedBy       string
	CreatedAt       time.Time
}

type MiskoWeightMeasurement struct {
	ID             string
	SubjectID      string
	BodyMilligrams int64
	MeasuredAt     time.Time
	RecordedBy     string
	CreatedAt      time.Time
}

type MiskoWorkerCapability struct {
	WorkerID        string
	ParadigmKey     string
	ParadigmVersion int32
}
