// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAsset = `-- name: CreateAsset :one
WITH new_asset AS (SELECT uuidv7() AS id)
INSERT INTO misko.video_assets (id, kind, bucket, object_name, content_type, file_name, size_bytes, crc32c, created_by)
SELECT n.id, 'ORIGINAL', $1::text, 'tests/' || $2::text || '/originals/' || n.id::text,
       $3::text, $4::text, $5::bigint, $6::bigint, $7::uuid
FROM new_asset n
RETURNING id, kind, bucket, object_name, content_type, file_name, size_bytes, crc32c, status, generation, rejection_reason, verified_at, created_by, created_at
`

type CreateAssetParams struct {
	Bucket      string
	TestID      string
	ContentType string
	FileName    *string
	SizeBytes   int64
	Crc32c      int64
	CreatedBy   string
}

// CreateAsset names the object after its test and its own id, so every upload
// gets a new object key.
func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (MiskoVideoAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.Bucket,
		arg.TestID,
		arg.ContentType,
		arg.FileName,
		arg.SizeBytes,
		arg.Crc32c,
		arg.CreatedBy,
	)
	var i MiskoVideoAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Bucket,
		&i.ObjectName,
		&i.ContentType,
		&i.FileName,
		&i.SizeBytes,
		&i.Crc32c,
		&i.Status,
		&i.Generation,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRecording = `-- name: CreateRecording :one
INSERT INTO misko.test_recordings (experiment_id, test_id, video_asset_id, clip_start_us, clip_end_us, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, experiment_id, test_id, video_asset_id, clip_start_us, clip_end_us, created_by, created_at
`

type CreateRecordingParams struct {
	ExperimentID string
	TestID       string
	VideoAssetID string
	ClipStartUs  int64
	ClipEndUs    *int64
	CreatedBy    string
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (MiskoTestRecording, error) {
	row := q.db.QueryRow(ctx, createRecording,
		arg.ExperimentID,
		arg.TestID,
		arg.VideoAssetID,
		arg.ClipStartUs,
		arg.ClipEndUs,
		arg.CreatedBy,
	)
	var i MiskoTestRecording
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.VideoAssetID,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const finishAsset = `-- name: FinishAsset :one
UPDATE misko.video_assets
SET status = $1, generation = $2, rejection_reason = $3, verified_at = $4
WHERE id = $5 AND status = 'PENDING'
RETURNING id, kind, bucket, object_name, content_type, file_name, size_bytes, crc32c, status, generation, rejection_reason, verified_at, created_by, created_at
`

type FinishAssetParams struct {
	Status          string
	Generation      *int64
	RejectionReason *string
	VerifiedAt      *time.Time
	ID              string
}

func (q *Queries) FinishAsset(ctx context.Context, arg FinishAssetParams) (MiskoVideoAsset, error) {
	row := q.db.QueryRow(ctx, finishAsset,
		arg.Status,
		arg.Generation,
		arg.RejectionReason,
		arg.VerifiedAt,
		arg.ID,
	)
	var i MiskoVideoAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Bucket,
		&i.ObjectName,
		&i.ContentType,
		&i.FileName,
		&i.SizeBytes,
		&i.Crc32c,
		&i.Status,
		&i.Generation,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRecording = `-- name: GetRecording :one
SELECT r.id, r.experiment_id, r.test_id, r.clip_start_us, r.clip_end_us, r.created_by, r.created_at,
       a.id AS asset_id, a.kind, a.bucket, a.object_name, a.content_type, a.file_name, a.size_bytes, a.crc32c,
       a.status, a.generation, a.rejection_reason, a.verified_at, a.created_by AS asset_created_by, a.created_at AS asset_created_at
FROM misko.test_recordings r
JOIN misko.video_assets a ON a.id = r.video_asset_id
WHERE r.test_id = $1 AND r.id = $2
`

type GetRecordingParams struct {
	TestID string
	ID     string
}

type GetRecordingRow struct {
	ID              string
	ExperimentID    string
	TestID          string
	ClipStartUs     int64
	ClipEndUs       *int64
	CreatedBy       string
	CreatedAt       time.Time
	AssetID         string
	Kind            string
	Bucket          string
	ObjectName      string
	ContentType     string
	FileName        *string
	SizeBytes       int64
	Crc32c          int64
	Status          string
	Generation      *int64
	RejectionReason *string
	VerifiedAt      *time.Time
	AssetCreatedBy  string
	AssetCreatedAt  time.Time
}

func (q *Queries) GetRecording(ctx context.Context, arg GetRecordingParams) (GetRecordingRow, error) {
	row := q.db.QueryRow(ctx, getRecording, arg.TestID, arg.ID)
	var i GetRecordingRow
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AssetID,
		&i.Kind,
		&i.Bucket,
		&i.ObjectName,
		&i.ContentType,
		&i.FileName,
		&i.SizeBytes,
		&i.Crc32c,
		&i.Status,
		&i.Generation,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.AssetCreatedBy,
		&i.AssetCreatedAt,
	)
	return i, err
}

const getTestRef = `-- name: GetTestRef :one
SELECT id, experiment_id, status FROM misko.tests WHERE id = $1
`

type GetTestRefRow struct {
	ID           string
	ExperimentID string
	Status       string
}

func (q *Queries) GetTestRef(ctx context.Context, id string) (GetTestRefRow, error) {
	row := q.db.QueryRow(ctx, getTestRef, id)
	var i GetTestRefRow
	err := row.Scan(&i.ID, &i.ExperimentID, &i.Status)
	return i, err
}

const listRecordings = `-- name: ListRecordings :many
SELECT r.id, r.experiment_id, r.test_id, r.clip_start_us, r.clip_end_us, r.created_by, r.created_at,
       a.id AS asset_id, a.kind, a.bucket, a.object_name, a.content_type, a.file_name, a.size_bytes, a.crc32c,
       a.status, a.generation, a.rejection_reason, a.verified_at, a.created_by AS asset_created_by, a.created_at AS asset_created_at
FROM misko.test_recordings r
JOIN misko.video_assets a ON a.id = r.video_asset_id
WHERE r.test_id = $1
ORDER BY r.created_at, r.id
`

type ListRecordingsRow struct {
	ID              string
	ExperimentID    string
	TestID          string
	ClipStartUs     int64
	ClipEndUs       *int64
	CreatedBy       string
	CreatedAt       time.Time
	AssetID         string
	Kind            string
	Bucket          string
	ObjectName      string
	ContentType     string
	FileName        *string
	SizeBytes       int64
	Crc32c          int64
	Status          string
	Generation      *int64
	RejectionReason *string
	VerifiedAt      *time.Time
	AssetCreatedBy  string
	AssetCreatedAt  time.Time
}

func (q *Queries) ListRecordings(ctx context.Context, testID string) ([]ListRecordingsRow, error) {
	rows, err := q.db.Query(ctx, listRecordings, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordingsRow
	for rows.Next() {
		var i ListRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.TestID,
			&i.ClipStartUs,
			&i.ClipEndUs,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.AssetID,
			&i.Kind,
			&i.Bucket,
			&i.ObjectName,
			&i.ContentType,
			&i.FileName,
			&i.SizeBytes,
			&i.Crc32c,
			&i.Status,
			&i.Generation,
			&i.RejectionReason,
			&i.VerifiedAt,
			&i.AssetCreatedBy,
			&i.AssetCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecording = `-- name: LockRecording :one
SELECT r.id, r.experiment_id, r.test_id, r.clip_start_us, r.clip_end_us, r.created_by, r.created_at,
       a.id AS asset_id, a.kind, a.bucket, a.object_name, a.content_type, a.file_name, a.size_bytes, a.crc32c,
       a.status, a.generation, a.rejection_reason, a.verified_at, a.created_by AS asset_created_by, a.created_at AS asset_created_at
FROM misko.test_recordings r
JOIN misko.video_assets a ON a.id = r.video_asset_id
WHERE r.test_id = $1 AND r.id = $2
FOR UPDATE OF a
`

type LockRecordingParams struct {
	TestID string
	ID     string
}

type LockRecordingRow struct {
	ID              string
	ExperimentID    string
	TestID          string
	ClipStartUs     int64
	ClipEndUs       *int64
	CreatedBy       string
	CreatedAt       time.Time
	AssetID         string
	Kind            string
	Bucket          string
	ObjectName      string
	ContentType     string
	FileName        *string
	SizeBytes       int64
	Crc32c          int64
	Status          string
	Generation      *int64
	RejectionReason *string
	VerifiedAt      *time.Time
	AssetCreatedBy  string
	AssetCreatedAt  time.Time
}

func (q *Queries) LockRecording(ctx context.Context, arg LockRecordingParams) (LockRecordingRow, error) {
	row := q.db.QueryRow(ctx, lockRecording, arg.TestID, arg.ID)
	var i LockRecordingRow
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AssetID,
		&i.Kind,
		&i.Bucket,
		&i.ObjectName,
		&i.ContentType,
		&i.FileName,
		&i.SizeBytes,
		&i.Crc32c,
		&i.Status,
		&i.Generation,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.AssetCreatedBy,
		&i.AssetCreatedAt,
	)
	return i, err
}
