// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM misko.users
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%' ESCAPE '\' OR email ILIKE '%' || $1::text || '%' ESCAPE '\')
  AND ($2::text = '' OR role = $2::text)
`

type CountUsersParams struct {
	Search string
	Role   string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithRoles = `-- name: CountUsersWithRoles :one
SELECT count(*)
FROM misko.users
WHERE role = ANY($1::text[])
`

func (q *Queries) CountUsersWithRoles(ctx context.Context, roles []string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithRoles, roles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO misko.users (email, name, role, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, role, created_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	Role         string
	PasswordHash string
}

type CreateUserRow struct {
	ID        string
	Email     string
	Name      string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM misko.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, name, role, created_at, password_hash, session_version
FROM misko.users
WHERE email = $1
`

type GetAccountByEmailRow struct {
	ID             string
	Email          string
	Name           string
	Role           string
	CreatedAt      time.Time
	PasswordHash   string
	SessionVersion int32
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.SessionVersion,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, name, role, created_at, password_hash, session_version
FROM misko.users
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID             string
	Email          string
	Name           string
	Role           string
	CreatedAt      time.Time
	PasswordHash   string
	SessionVersion int32
}

func (q *Queries) GetAccountByID(ctx context.Context, id string) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.SessionVersion,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, role, created_at
FROM misko.users
WHERE id = $1
`

type GetUserRow struct {
	ID        string
	Email     string
	Name      string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, created_at
FROM misko.users
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%' ESCAPE '\' OR email ILIKE '%' || $1::text || '%' ESCAPE '\')
  AND ($2::text = '' OR role = $2::text)
ORDER BY
    CASE WHEN $3::text = 'name' AND NOT $4::boolean THEN name END ASC,
    CASE WHEN $3::text = 'name' AND $4::boolean THEN name END DESC,
    CASE WHEN $3::text = 'email' AND NOT $4::boolean THEN email END ASC,
    CASE WHEN $3::text = 'email' AND $4::boolean THEN email END DESC,
    CASE WHEN $3::text = 'role' AND NOT $4::boolean THEN role END ASC,
    CASE WHEN $3::text = 'role' AND $4::boolean THEN role END DESC,
    CASE WHEN $3::text = 'createdAt' AND NOT $4::boolean THEN created_at END ASC,
    CASE WHEN $3::text = 'createdAt' AND $4::boolean THEN created_at END DESC,
    id ASC
LIMIT $6::integer OFFSET $5::integer
`

type ListUsersParams struct {
	Search     string
	Role       string
	SortKey    string
	Descending bool
	PageOffset int32
	PageLimit  int32
}

type ListUsersRow struct {
	ID        string
	Email     string
	Name      string
	Role      string
	CreatedAt time.Time
}

// The sort key is allowlisted by the application; id breaks ties for stable paging.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.SortKey,
		arg.Descending,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPasswordHash = `-- name: SetPasswordHash :one
UPDATE misko.users
SET password_hash = $1,
    session_version = session_version + 1,
    updated_at = now()
WHERE id = $2
RETURNING session_version
`

type SetPasswordHashParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (int32, error) {
	row := q.db.QueryRow(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	var session_version int32
	err := row.Scan(&session_version)
	return session_version, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE misko.users
SET name = coalesce($1, name),
    role = coalesce($2, role),
    updated_at = now()
WHERE id = $3
RETURNING id, email, name, role, created_at
`

type UpdateUserParams struct {
	Name *string
	Role *string
	ID   string
}

type UpdateUserRow struct {
	ID        string
	Email     string
	Name      string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.Role, arg.ID)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
