"""Writes the cross-language contract fixture used by the Go analysis tests.

    python -m tests.contract_fixture ../backend/internal/analysis/adapters/catalog/testdata/worker_open_field_walk.json

It renders the synthetic walk (6 s at 25 fps), runs the worker pipeline and
stores the trajectory the worker would upload, together with the ground truth
the Go test compares the engine's metrics and events with. Regenerate it when
the trajectory format or the algorithm changes.
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

from misko_worker import ALGORITHM_VERSION
from misko_worker.pipeline import analyze, trajectory_document
from tests import synthetic


def main(destination: str) -> None:
    with tempfile.TemporaryDirectory() as scratch:
        source = Path(scratch) / "walk.mp4"
        truth = synthetic.render(source, synthetic.regular(6.0))
        job = synthetic.job(run_id="01a00000-0000-7000-8000-00000000f1f1")
        analysis = analyze(source, job, Path(scratch) / "overlay.mp4")
        trajectory = json.loads(trajectory_document(job, analysis))
    fixture = {
        "description": "Synthetic walk: 0-2 s east along y=10 cm, 2-3.5 s still, 3.5-5 s to the center, then still. Generated by worker/tests/contract_fixture.py.",
        "algorithm": ALGORITHM_VERSION,
        "parameters": job["run"]["parameters"],
        "truth": {"tUs": [t.t_us for t in truth], "xCm": [round(t.x, 6) for t in truth], "yCm": [round(t.y, 6) for t in truth]},
        "trajectory": trajectory,
    }
    Path(destination).write_text(json.dumps(fixture, separators=(",", ":")) + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
