// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const createProtocol = `-- name: CreateProtocol :one
INSERT INTO misko.protocols (experiment_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, experiment_id, name, description, created_at, updated_at
`

type CreateProtocolParams struct {
	ExperimentID string
	Name         string
	Description  *string
}

func (q *Queries) CreateProtocol(ctx context.Context, arg CreateProtocolParams) (MiskoProtocol, error) {
	row := q.db.QueryRow(ctx, createProtocol, arg.ExperimentID, arg.Name, arg.Description)
	var i MiskoProtocol
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStep = `-- name: CreateStep :exec
INSERT INTO misko.protocol_steps (protocol_version_id, position, paradigm_key, paradigm_version, environment_revision_id, trial_type, trials, inter_trial_interval_s, session, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateStepParams struct {
	ProtocolVersionID     string
	Position              int32
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	TrialType             string
	Trials                int32
	InterTrialIntervalS   int32
	Session               []byte
	Notes                 *string
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) error {
	_, err := q.db.Exec(ctx, createStep,
		arg.ProtocolVersionID,
		arg.Position,
		arg.ParadigmKey,
		arg.ParadigmVersion,
		arg.EnvironmentRevisionID,
		arg.TrialType,
		arg.Trials,
		arg.InterTrialIntervalS,
		arg.Session,
		arg.Notes,
	)
	return err
}

const createVersion = `-- name: CreateVersion :one
INSERT INTO misko.protocol_versions (experiment_id, protocol_id, number, step_count, notes, created_by)
SELECT $1::uuid, $2::uuid, coalesce(max(v.number), 0) + 1, $3::integer, $4::text, $5::uuid
FROM misko.protocol_versions v
WHERE v.protocol_id = $2::uuid
RETURNING id, experiment_id, protocol_id, number, step_count, notes, created_by, created_at
`

type CreateVersionParams struct {
	ExperimentID string
	ProtocolID   string
	StepCount    int32
	Notes        *string
	CreatedBy    string
}

// CreateVersion numbers versions per protocol; callers lock the protocol or
// create it in the same transaction.
func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) (MiskoProtocolVersion, error) {
	row := q.db.QueryRow(ctx, createVersion,
		arg.ExperimentID,
		arg.ProtocolID,
		arg.StepCount,
		arg.Notes,
		arg.CreatedBy,
	)
	var i MiskoProtocolVersion
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.ProtocolID,
		&i.Number,
		&i.StepCount,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentRevision = `-- name: GetEnvironmentRevision :one
SELECT id, environment_id, number, paradigm_key, paradigm_version, apparatus
FROM misko.environment_revisions
WHERE id = $1
`

type GetEnvironmentRevisionRow struct {
	ID              string
	EnvironmentID   string
	Number          int32
	ParadigmKey     string
	ParadigmVersion int32
	Apparatus       []byte
}

func (q *Queries) GetEnvironmentRevision(ctx context.Context, id string) (GetEnvironmentRevisionRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentRevision, id)
	var i GetEnvironmentRevisionRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Number,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.Apparatus,
	)
	return i, err
}

const getProtocol = `-- name: GetProtocol :one
SELECT p.id, p.experiment_id, p.name, p.description, p.created_at, p.updated_at,
       coalesce((SELECT max(v.number) FROM misko.protocol_versions v WHERE v.protocol_id = p.id), 0)::integer AS latest_version
FROM misko.protocols p
WHERE p.experiment_id = $1 AND p.id = $2
`

type GetProtocolParams struct {
	ExperimentID string
	ID           string
}

type GetProtocolRow struct {
	ID            string
	ExperimentID  string
	Name          string
	Description   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LatestVersion int32
}

func (q *Queries) GetProtocol(ctx context.Context, arg GetProtocolParams) (GetProtocolRow, error) {
	row := q.db.QueryRow(ctx, getProtocol, arg.ExperimentID, arg.ID)
	var i GetProtocolRow
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestVersion,
	)
	return i, err
}

const getVersion = `-- name: GetVersion :one
SELECT id, experiment_id, protocol_id, number, step_count, notes, created_by, created_at
FROM misko.protocol_versions
WHERE experiment_id = $1 AND protocol_id = $2 AND number = $3
`

type GetVersionParams struct {
	ExperimentID string
	ProtocolID   string
	Number       int32
}

func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (MiskoProtocolVersion, error) {
	row := q.db.QueryRow(ctx, getVersion, arg.ExperimentID, arg.ProtocolID, arg.Number)
	var i MiskoProtocolVersion
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.ProtocolID,
		&i.Number,
		&i.StepCount,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listProtocols = `-- name: ListProtocols :many
SELECT p.id, p.experiment_id, p.name, p.description, p.created_at, p.updated_at,
       coalesce((SELECT max(v.number) FROM misko.protocol_versions v WHERE v.protocol_id = p.id), 0)::integer AS latest_version
FROM misko.protocols p
WHERE p.experiment_id = $1
ORDER BY lower(p.name), p.id
`

type ListProtocolsRow struct {
	ID            string
	ExperimentID  string
	Name          string
	Description   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LatestVersion int32
}

func (q *Queries) ListProtocols(ctx context.Context, experimentID string) ([]ListProtocolsRow, error) {
	rows, err := q.db.Query(ctx, listProtocols, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProtocolsRow
	for rows.Next() {
		var i ListProtocolsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSteps = `-- name: ListSteps :many
SELECT s.protocol_version_id, s.position, s.paradigm_key, s.paradigm_version, s.environment_revision_id,
       r.environment_id, r.number AS environment_revision, s.trial_type, s.trials, s.inter_trial_interval_s, s.session, s.notes
FROM misko.protocol_steps s
JOIN misko.environment_revisions r ON r.id = s.environment_revision_id
WHERE s.protocol_version_id = ANY($1::uuid[])
ORDER BY s.protocol_version_id, s.position
`

type ListStepsRow struct {
	ProtocolVersionID     string
	Position              int32
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	EnvironmentID         string
	EnvironmentRevision   int32
	TrialType             string
	Trials                int32
	InterTrialIntervalS   int32
	Session               []byte
	Notes                 *string
}

func (q *Queries) ListSteps(ctx context.Context, versionIds []string) ([]ListStepsRow, error) {
	rows, err := q.db.Query(ctx, listSteps, versionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStepsRow
	for rows.Next() {
		var i ListStepsRow
		if err := rows.Scan(
			&i.ProtocolVersionID,
			&i.Position,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.EnvironmentRevisionID,
			&i.EnvironmentID,
			&i.EnvironmentRevision,
			&i.TrialType,
			&i.Trials,
			&i.InterTrialIntervalS,
			&i.Session,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT id, experiment_id, protocol_id, number, step_count, notes, created_by, created_at
FROM misko.protocol_versions
WHERE experiment_id = $1 AND protocol_id = $2
ORDER BY number
`

type ListVersionsParams struct {
	ExperimentID string
	ProtocolID   string
}

func (q *Queries) ListVersions(ctx context.Context, arg ListVersionsParams) ([]MiskoProtocolVersion, error) {
	rows, err := q.db.Query(ctx, listVersions, arg.ExperimentID, arg.ProtocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoProtocolVersion
	for rows.Next() {
		var i MiskoProtocolVersion
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.ProtocolID,
			&i.Number,
			&i.StepCount,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProtocol = `-- name: LockProtocol :one
SELECT id, experiment_id, name, description, created_at, updated_at
FROM misko.protocols
WHERE experiment_id = $1 AND id = $2
FOR UPDATE
`

type LockProtocolParams struct {
	ExperimentID string
	ID           string
}

func (q *Queries) LockProtocol(ctx context.Context, arg LockProtocolParams) (MiskoProtocol, error) {
	row := q.db.QueryRow(ctx, lockProtocol, arg.ExperimentID, arg.ID)
	var i MiskoProtocol
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProtocol = `-- name: UpdateProtocol :one
UPDATE misko.protocols AS p
SET name = coalesce($1, p.name),
    description = CASE WHEN $2::text IS NULL THEN p.description ELSE NULLIF($2::text, '') END,
    updated_at = now()
WHERE p.experiment_id = $3 AND p.id = $4
RETURNING p.id, p.experiment_id, p.name, p.description, p.created_at, p.updated_at,
          coalesce((SELECT max(v.number) FROM misko.protocol_versions v WHERE v.protocol_id = p.id), 0)::integer AS latest_version
`

type UpdateProtocolParams struct {
	Name         *string
	Description  *string
	ExperimentID string
	ID           string
}

type UpdateProtocolRow struct {
	ID            string
	ExperimentID  string
	Name          string
	Description   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LatestVersion int32
}

func (q *Queries) UpdateProtocol(ctx context.Context, arg UpdateProtocolParams) (UpdateProtocolRow, error) {
	row := q.db.QueryRow(ctx, updateProtocol,
		arg.Name,
		arg.Description,
		arg.ExperimentID,
		arg.ID,
	)
	var i UpdateProtocolRow
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestVersion,
	)
	return i, err
}
