// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const activeCapabilities = `-- name: ActiveCapabilities :many
SELECT DISTINCT c.paradigm_key, c.paradigm_version
FROM misko.worker_capabilities c
JOIN misko.analysis_workers w ON w.id = c.worker_id
WHERE w.disabled_at IS NULL
ORDER BY c.paradigm_key, c.paradigm_version
`

type ActiveCapabilitiesRow struct {
	ParadigmKey     string
	ParadigmVersion int32
}

func (q *Queries) ActiveCapabilities(ctx context.Context) ([]ActiveCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, activeCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveCapabilitiesRow
	for rows.Next() {
		var i ActiveCapabilitiesRow
		if err := rows.Scan(&i.ParadigmKey, &i.ParadigmVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addCapability = `-- name: AddCapability :exec
INSERT INTO misko.worker_capabilities (worker_id, paradigm_key, paradigm_version)
VALUES ($1, $2, $3)
`

type AddCapabilityParams struct {
	WorkerID        string
	ParadigmKey     string
	ParadigmVersion int32
}

func (q *Queries) AddCapability(ctx context.Context, arg AddCapabilityParams) error {
	_, err := q.db.Exec(ctx, addCapability, arg.WorkerID, arg.ParadigmKey, arg.ParadigmVersion)
	return err
}

const claimNext = `-- name: ClaimNext :one
SELECT id, experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us, calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id, parameters, trigger, status, attempt, max_attempts, worker_id, lease_expires_at, available_at, model_version, failure_reason, created_by, created_at, finished_at FROM misko.analysis_runs r
WHERE r.status = 'QUEUED' AND r.available_at <= $1::timestamptz
  AND (r.paradigm_key || '@' || r.paradigm_version::text) = ANY($2::text[])
ORDER BY r.available_at, r.id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type ClaimNextParams struct {
	Now          time.Time
	Capabilities []string
}

// ClaimNext takes the oldest available run for a capability ("KEY@version"),
// skipping runs another worker is claiming.
func (q *Queries) ClaimNext(ctx context.Context, arg ClaimNextParams) (MiskoAnalysisRun, error) {
	row := q.db.QueryRow(ctx, claimNext, arg.Now, arg.Capabilities)
	var i MiskoAnalysisRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.RecordingID,
		&i.SourceAssetID,
		&i.SourceGeneration,
		&i.SourceCrc32c,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CalibrationID,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.MetricEngineVersion,
		&i.ResultSchemaVersion,
		&i.EnvironmentRevisionID,
		&i.ProtocolVersionID,
		&i.Parameters,
		&i.Trigger,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.ModelVersion,
		&i.FailureReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createAnalyzedAsset = `-- name: CreateAnalyzedAsset :one
INSERT INTO misko.video_assets (kind, bucket, object_name, content_type, size_bytes, crc32c, status, generation, verified_at, created_by)
VALUES ('ANALYZED', $1, $2, $3, $4, $5, 'VERIFIED', $6, $7, $8)
RETURNING id
`

type CreateAnalyzedAssetParams struct {
	Bucket      string
	ObjectName  string
	ContentType string
	SizeBytes   int64
	Crc32c      int64
	Generation  *int64
	VerifiedAt  *time.Time
	CreatedBy   string
}

func (q *Queries) CreateAnalyzedAsset(ctx context.Context, arg CreateAnalyzedAssetParams) (string, error) {
	row := q.db.QueryRow(ctx, createAnalyzedAsset,
		arg.Bucket,
		arg.ObjectName,
		arg.ContentType,
		arg.SizeBytes,
		arg.Crc32c,
		arg.Generation,
		arg.VerifiedAt,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createArtifact = `-- name: CreateArtifact :exec
INSERT INTO misko.analysis_artifacts (run_id, attempt, object_name, kind, bucket, generation, size_bytes, crc32c, content_type, video_asset_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateArtifactParams struct {
	RunID        string
	Attempt      int32
	ObjectName   string
	Kind         string
	Bucket       string
	Generation   int64
	SizeBytes    int64
	Crc32c       int64
	ContentType  string
	VideoAssetID *string
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) error {
	_, err := q.db.Exec(ctx, createArtifact,
		arg.RunID,
		arg.Attempt,
		arg.ObjectName,
		arg.Kind,
		arg.Bucket,
		arg.Generation,
		arg.SizeBytes,
		arg.Crc32c,
		arg.ContentType,
		arg.VideoAssetID,
	)
	return err
}

const createAutomaticRun = `-- name: CreateAutomaticRun :execrows
INSERT INTO misko.analysis_runs (experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us,
    calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id,
    parameters, trigger, status, max_attempts, available_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, 'AUTOMATIC', 'QUEUED', $17, $18, NULL)
ON CONFLICT DO NOTHING
`

type CreateAutomaticRunParams struct {
	ExperimentID          string
	TestID                string
	RecordingID           string
	SourceAssetID         string
	SourceGeneration      int64
	SourceCrc32c          int64
	ClipStartUs           int64
	ClipEndUs             *int64
	CalibrationID         *string
	ParadigmKey           string
	ParadigmVersion       int32
	MetricEngineVersion   int32
	ResultSchemaVersion   int32
	EnvironmentRevisionID string
	ProtocolVersionID     string
	Parameters            []byte
	MaxAttempts           int32
	AvailableAt           time.Time
}

func (q *Queries) CreateAutomaticRun(ctx context.Context, arg CreateAutomaticRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAutomaticRun,
		arg.ExperimentID,
		arg.TestID,
		arg.RecordingID,
		arg.SourceAssetID,
		arg.SourceGeneration,
		arg.SourceCrc32c,
		arg.ClipStartUs,
		arg.ClipEndUs,
		arg.CalibrationID,
		arg.ParadigmKey,
		arg.ParadigmVersion,
		arg.MetricEngineVersion,
		arg.ResultSchemaVersion,
		arg.EnvironmentRevisionID,
		arg.ProtocolVersionID,
		arg.Parameters,
		arg.MaxAttempts,
		arg.AvailableAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO misko.analysis_events (run_id, attempt, test_id, event_type, kind, start_us, end_us, confidence, trial_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateEventParams struct {
	RunID      string
	Attempt    int32
	TestID     string
	EventType  string
	Kind       string
	StartUs    int64
	EndUs      int64
	Confidence float32
	TrialID    *string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.RunID,
		arg.Attempt,
		arg.TestID,
		arg.EventType,
		arg.Kind,
		arg.StartUs,
		arg.EndUs,
		arg.Confidence,
		arg.TrialID,
	)
	return err
}

const createManualRun = `-- name: CreateManualRun :one
INSERT INTO misko.analysis_runs (experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us,
    calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id,
    parameters, trigger, status, max_attempts, available_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, 'MANUAL', 'QUEUED', $17, $18, $19)
RETURNING id, experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us, calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id, parameters, trigger, status, attempt, max_attempts, worker_id, lease_expires_at, available_at, model_version, failure_reason, created_by, created_at, finished_at
`

type CreateManualRunParams struct {
	ExperimentID          string
	TestID                string
	RecordingID           string
	SourceAssetID         string
	SourceGeneration      int64
	SourceCrc32c          int64
	ClipStartUs           int64
	ClipEndUs             *int64
	CalibrationID         *string
	ParadigmKey           string
	ParadigmVersion       int32
	MetricEngineVersion   int32
	ResultSchemaVersion   int32
	EnvironmentRevisionID string
	ProtocolVersionID     string
	Parameters            []byte
	MaxAttempts           int32
	AvailableAt           time.Time
	CreatedBy             *string
}

func (q *Queries) CreateManualRun(ctx context.Context, arg CreateManualRunParams) (MiskoAnalysisRun, error) {
	row := q.db.QueryRow(ctx, createManualRun,
		arg.ExperimentID,
		arg.TestID,
		arg.RecordingID,
		arg.SourceAssetID,
		arg.SourceGeneration,
		arg.SourceCrc32c,
		arg.ClipStartUs,
		arg.ClipEndUs,
		arg.CalibrationID,
		arg.ParadigmKey,
		arg.ParadigmVersion,
		arg.MetricEngineVersion,
		arg.ResultSchemaVersion,
		arg.EnvironmentRevisionID,
		arg.ProtocolVersionID,
		arg.Parameters,
		arg.MaxAttempts,
		arg.AvailableAt,
		arg.CreatedBy,
	)
	var i MiskoAnalysisRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.RecordingID,
		&i.SourceAssetID,
		&i.SourceGeneration,
		&i.SourceCrc32c,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CalibrationID,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.MetricEngineVersion,
		&i.ResultSchemaVersion,
		&i.EnvironmentRevisionID,
		&i.ProtocolVersionID,
		&i.Parameters,
		&i.Trigger,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.ModelVersion,
		&i.FailureReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createMetric = `-- name: CreateMetric :exec
INSERT INTO misko.metric_results (run_id, attempt, metric_key, unit, value, missing_reason)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMetricParams struct {
	RunID         string
	Attempt       int32
	MetricKey     string
	Unit          string
	Value         *float64
	MissingReason *string
}

func (q *Queries) CreateMetric(ctx context.Context, arg CreateMetricParams) error {
	_, err := q.db.Exec(ctx, createMetric,
		arg.RunID,
		arg.Attempt,
		arg.MetricKey,
		arg.Unit,
		arg.Value,
		arg.MissingReason,
	)
	return err
}

const createOutputUpload = `-- name: CreateOutputUpload :exec
INSERT INTO misko.analysis_output_uploads (run_id, attempt, object_name, kind, content_type, size_bytes, crc32c)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOutputUploadParams struct {
	RunID       string
	Attempt     int32
	ObjectName  string
	Kind        string
	ContentType string
	SizeBytes   int64
	Crc32c      int64
}

func (q *Queries) CreateOutputUpload(ctx context.Context, arg CreateOutputUploadParams) error {
	_, err := q.db.Exec(ctx, createOutputUpload,
		arg.RunID,
		arg.Attempt,
		arg.ObjectName,
		arg.Kind,
		arg.ContentType,
		arg.SizeBytes,
		arg.Crc32c,
	)
	return err
}

const createPair = `-- name: CreatePair :exec
INSERT INTO misko.analysis_video_pairs (run_id, attempt, source_asset_id, source_generation, analyzed_asset_id, source_offset_us, output_offset_us, time_mapping_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePairParams struct {
	RunID              string
	Attempt            int32
	SourceAssetID      string
	SourceGeneration   int64
	AnalyzedAssetID    string
	SourceOffsetUs     int64
	OutputOffsetUs     int64
	TimeMappingVersion string
}

func (q *Queries) CreatePair(ctx context.Context, arg CreatePairParams) error {
	_, err := q.db.Exec(ctx, createPair,
		arg.RunID,
		arg.Attempt,
		arg.SourceAssetID,
		arg.SourceGeneration,
		arg.AnalyzedAssetID,
		arg.SourceOffsetUs,
		arg.OutputOffsetUs,
		arg.TimeMappingVersion,
	)
	return err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO misko.analysis_workers (name, model_version, token_sha256, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, model_version, disabled_at, created_by, created_at
`

type CreateWorkerParams struct {
	Name         string
	ModelVersion string
	TokenSha256  []byte
	CreatedBy    string
}

type CreateWorkerRow struct {
	ID           string
	Name         string
	ModelVersion string
	DisabledAt   *time.Time
	CreatedBy    string
	CreatedAt    time.Time
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (CreateWorkerRow, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.Name,
		arg.ModelVersion,
		arg.TokenSha256,
		arg.CreatedBy,
	)
	var i CreateWorkerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModelVersion,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const disableWorker = `-- name: DisableWorker :one
UPDATE misko.analysis_workers
SET disabled_at = coalesce(disabled_at, $1::timestamptz)
WHERE id = $2
RETURNING id, name, model_version, disabled_at, created_by, created_at
`

type DisableWorkerParams struct {
	At time.Time
	ID string
}

type DisableWorkerRow struct {
	ID           string
	Name         string
	ModelVersion string
	DisabledAt   *time.Time
	CreatedBy    string
	CreatedAt    time.Time
}

func (q *Queries) DisableWorker(ctx context.Context, arg DisableWorkerParams) (DisableWorkerRow, error) {
	row := q.db.QueryRow(ctx, disableWorker, arg.At, arg.ID)
	var i DisableWorkerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModelVersion,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCalibration = `-- name: GetCalibration :one
SELECT id, frame_width, frame_height, crop_x, crop_y, crop_width, crop_height, measurement_plane, transform
FROM misko.calibrations
WHERE id = $1
`

type GetCalibrationRow struct {
	ID               string
	FrameWidth       int32
	FrameHeight      int32
	CropX            int32
	CropY            int32
	CropWidth        int32
	CropHeight       int32
	MeasurementPlane string
	Transform        []float64
}

func (q *Queries) GetCalibration(ctx context.Context, id string) (GetCalibrationRow, error) {
	row := q.db.QueryRow(ctx, getCalibration, id)
	var i GetCalibrationRow
	err := row.Scan(
		&i.ID,
		&i.FrameWidth,
		&i.FrameHeight,
		&i.CropX,
		&i.CropY,
		&i.CropWidth,
		&i.CropHeight,
		&i.MeasurementPlane,
		&i.Transform,
	)
	return i, err
}

const getCandidate = `-- name: GetCandidate :one
SELECT r.experiment_id, r.test_id, r.id AS recording_id, a.id AS source_asset_id, coalesce(a.generation, 0)::bigint AS source_generation,
       a.crc32c AS source_crc32c, r.clip_start_us, r.clip_end_us, t.paradigm_key, t.paradigm_version,
       t.environment_revision_id, t.protocol_version_id, e.apparatus, s.session, a.status AS video_status, t.status AS test_status,
       coalesce(ec.calibration_id::text, '')::text AS calibration_id
FROM misko.test_recordings r
JOIN misko.effective_calibrations ec ON ec.recording_id = r.id
JOIN misko.video_assets a ON a.id = r.video_asset_id
JOIN misko.tests t ON t.id = r.test_id
JOIN misko.environment_revisions e ON e.id = t.environment_revision_id
JOIN misko.protocol_steps s ON s.protocol_version_id = t.protocol_version_id AND s.position = t.step_position
WHERE r.test_id = $1 AND r.id = $2
`

type GetCandidateParams struct {
	TestID string
	ID     string
}

type GetCandidateRow struct {
	ExperimentID          string
	TestID                string
	RecordingID           string
	SourceAssetID         string
	SourceGeneration      int64
	SourceCrc32c          int64
	ClipStartUs           int64
	ClipEndUs             *int64
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	ProtocolVersionID     string
	Apparatus             []byte
	Session               []byte
	VideoStatus           string
	TestStatus            string
	CalibrationID         string
}

func (q *Queries) GetCandidate(ctx context.Context, arg GetCandidateParams) (GetCandidateRow, error) {
	row := q.db.QueryRow(ctx, getCandidate, arg.TestID, arg.ID)
	var i GetCandidateRow
	err := row.Scan(
		&i.ExperimentID,
		&i.TestID,
		&i.RecordingID,
		&i.SourceAssetID,
		&i.SourceGeneration,
		&i.SourceCrc32c,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.EnvironmentRevisionID,
		&i.ProtocolVersionID,
		&i.Apparatus,
		&i.Session,
		&i.VideoStatus,
		&i.TestStatus,
		&i.CalibrationID,
	)
	return i, err
}

const getPair = `-- name: GetPair :one
SELECT p.source_asset_id, p.source_generation, s.object_name AS source_object_name, p.analyzed_asset_id, a.object_name AS analyzed_object_name,
       a.generation AS analyzed_generation, p.source_offset_us, p.output_offset_us, p.time_mapping_version
FROM misko.analysis_video_pairs p
JOIN misko.video_assets s ON s.id = p.source_asset_id
JOIN misko.video_assets a ON a.id = p.analyzed_asset_id
WHERE p.run_id = $1
`

type GetPairRow struct {
	SourceAssetID      string
	SourceGeneration   int64
	SourceObjectName   string
	AnalyzedAssetID    string
	AnalyzedObjectName string
	AnalyzedGeneration *int64
	SourceOffsetUs     int64
	OutputOffsetUs     int64
	TimeMappingVersion string
}

func (q *Queries) GetPair(ctx context.Context, runID string) (GetPairRow, error) {
	row := q.db.QueryRow(ctx, getPair, runID)
	var i GetPairRow
	err := row.Scan(
		&i.SourceAssetID,
		&i.SourceGeneration,
		&i.SourceObjectName,
		&i.AnalyzedAssetID,
		&i.AnalyzedObjectName,
		&i.AnalyzedGeneration,
		&i.SourceOffsetUs,
		&i.OutputOffsetUs,
		&i.TimeMappingVersion,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us, calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id, parameters, trigger, status, attempt, max_attempts, worker_id, lease_expires_at, available_at, model_version, failure_reason, created_by, created_at, finished_at FROM misko.analysis_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id string) (MiskoAnalysisRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i MiskoAnalysisRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.RecordingID,
		&i.SourceAssetID,
		&i.SourceGeneration,
		&i.SourceCrc32c,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CalibrationID,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.MetricEngineVersion,
		&i.ResultSchemaVersion,
		&i.EnvironmentRevisionID,
		&i.ProtocolVersionID,
		&i.Parameters,
		&i.Trigger,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.ModelVersion,
		&i.FailureReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT run_id, attempt, object_name, kind, bucket, generation, size_bytes, crc32c, content_type FROM misko.analysis_artifacts WHERE run_id = $1 ORDER BY object_name
`

type ListArtifactsRow struct {
	RunID       string
	Attempt     int32
	ObjectName  string
	Kind        string
	Bucket      string
	Generation  int64
	SizeBytes   int64
	Crc32c      int64
	ContentType string
}

func (q *Queries) ListArtifacts(ctx context.Context, runID string) ([]ListArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listArtifacts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtifactsRow
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(
			&i.RunID,
			&i.Attempt,
			&i.ObjectName,
			&i.Kind,
			&i.Bucket,
			&i.Generation,
			&i.SizeBytes,
			&i.Crc32c,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT worker_id, paradigm_key, paradigm_version
FROM misko.worker_capabilities
ORDER BY worker_id, paradigm_key, paradigm_version
`

func (q *Queries) ListCapabilities(ctx context.Context) ([]MiskoWorkerCapability, error) {
	rows, err := q.db.Query(ctx, listCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoWorkerCapability
	for rows.Next() {
		var i MiskoWorkerCapability
		if err := rows.Scan(&i.WorkerID, &i.ParadigmKey, &i.ParadigmVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT event_type, kind, start_us, end_us, confidence, trial_id FROM misko.analysis_events WHERE run_id = $1 ORDER BY start_us, event_type, end_us
`

type ListEventsRow struct {
	EventType  string
	Kind       string
	StartUs    int64
	EndUs      int64
	Confidence float32
	TrialID    *string
}

func (q *Queries) ListEvents(ctx context.Context, runID string) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.Kind,
			&i.StartUs,
			&i.EndUs,
			&i.Confidence,
			&i.TrialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetrics = `-- name: ListMetrics :many
SELECT metric_key, unit, value, missing_reason FROM misko.metric_results WHERE run_id = $1 ORDER BY metric_key
`

type ListMetricsRow struct {
	MetricKey     string
	Unit          string
	Value         *float64
	MissingReason *string
}

func (q *Queries) ListMetrics(ctx context.Context, runID string) ([]ListMetricsRow, error) {
	rows, err := q.db.Query(ctx, listMetrics, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetricsRow
	for rows.Next() {
		var i ListMetricsRow
		if err := rows.Scan(
			&i.MetricKey,
			&i.Unit,
			&i.Value,
			&i.MissingReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us, calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id, parameters, trigger, status, attempt, max_attempts, worker_id, lease_expires_at, available_at, model_version, failure_reason, created_by, created_at, finished_at FROM misko.analysis_runs WHERE test_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRuns(ctx context.Context, testID string) ([]MiskoAnalysisRun, error) {
	rows, err := q.db.Query(ctx, listRuns, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoAnalysisRun
	for rows.Next() {
		var i MiskoAnalysisRun
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.TestID,
			&i.RecordingID,
			&i.SourceAssetID,
			&i.SourceGeneration,
			&i.SourceCrc32c,
			&i.ClipStartUs,
			&i.ClipEndUs,
			&i.CalibrationID,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.MetricEngineVersion,
			&i.ResultSchemaVersion,
			&i.EnvironmentRevisionID,
			&i.ProtocolVersionID,
			&i.Parameters,
			&i.Trigger,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.WorkerID,
			&i.LeaseExpiresAt,
			&i.AvailableAt,
			&i.ModelVersion,
			&i.FailureReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, model_version, disabled_at, created_by, created_at
FROM misko.analysis_workers
ORDER BY lower(name), id
`

type ListWorkersRow struct {
	ID           string
	Name         string
	ModelVersion string
	DisabledAt   *time.Time
	CreatedBy    string
	CreatedAt    time.Time
}

func (q *Queries) ListWorkers(ctx context.Context) ([]ListWorkersRow, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkersRow
	for rows.Next() {
		var i ListWorkersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ModelVersion,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpiredRuns = `-- name: LockExpiredRuns :many
SELECT id, experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us, calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id, parameters, trigger, status, attempt, max_attempts, worker_id, lease_expires_at, available_at, model_version, failure_reason, created_by, created_at, finished_at FROM misko.analysis_runs
WHERE status = 'RUNNING' AND lease_expires_at < $1::timestamptz
ORDER BY lease_expires_at, id
LIMIT 100
FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockExpiredRuns(ctx context.Context, now time.Time) ([]MiskoAnalysisRun, error) {
	rows, err := q.db.Query(ctx, lockExpiredRuns, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoAnalysisRun
	for rows.Next() {
		var i MiskoAnalysisRun
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.TestID,
			&i.RecordingID,
			&i.SourceAssetID,
			&i.SourceGeneration,
			&i.SourceCrc32c,
			&i.ClipStartUs,
			&i.ClipEndUs,
			&i.CalibrationID,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.MetricEngineVersion,
			&i.ResultSchemaVersion,
			&i.EnvironmentRevisionID,
			&i.ProtocolVersionID,
			&i.Parameters,
			&i.Trigger,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.WorkerID,
			&i.LeaseExpiresAt,
			&i.AvailableAt,
			&i.ModelVersion,
			&i.FailureReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecordingRuns = `-- name: LockRecordingRuns :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// LockRecordingRuns serializes run creation for one recording until the
// transaction ends, so two requests cannot both see no pending run.
func (q *Queries) LockRecordingRuns(ctx context.Context, recordingID string) error {
	_, err := q.db.Exec(ctx, lockRecordingRuns, recordingID)
	return err
}

const lockRun = `-- name: LockRun :one
SELECT id, experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us, calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id, parameters, trigger, status, attempt, max_attempts, worker_id, lease_expires_at, available_at, model_version, failure_reason, created_by, created_at, finished_at FROM misko.analysis_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRun(ctx context.Context, id string) (MiskoAnalysisRun, error) {
	row := q.db.QueryRow(ctx, lockRun, id)
	var i MiskoAnalysisRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.RecordingID,
		&i.SourceAssetID,
		&i.SourceGeneration,
		&i.SourceCrc32c,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CalibrationID,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.MetricEngineVersion,
		&i.ResultSchemaVersion,
		&i.EnvironmentRevisionID,
		&i.ProtocolVersionID,
		&i.Parameters,
		&i.Trigger,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.ModelVersion,
		&i.FailureReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const outputUploads = `-- name: OutputUploads :many
SELECT run_id, attempt, object_name, kind, content_type, size_bytes, crc32c
FROM misko.analysis_output_uploads
WHERE run_id = $1 AND attempt = $2
ORDER BY object_name
`

type OutputUploadsParams struct {
	RunID   string
	Attempt int32
}

type OutputUploadsRow struct {
	RunID       string
	Attempt     int32
	ObjectName  string
	Kind        string
	ContentType string
	SizeBytes   int64
	Crc32c      int64
}

func (q *Queries) OutputUploads(ctx context.Context, arg OutputUploadsParams) ([]OutputUploadsRow, error) {
	rows, err := q.db.Query(ctx, outputUploads, arg.RunID, arg.Attempt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutputUploadsRow
	for rows.Next() {
		var i OutputUploadsRow
		if err := rows.Scan(
			&i.RunID,
			&i.Attempt,
			&i.ObjectName,
			&i.Kind,
			&i.ContentType,
			&i.SizeBytes,
			&i.Crc32c,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingRunExists = `-- name: PendingRunExists :one
SELECT EXISTS (SELECT 1 FROM misko.analysis_runs WHERE recording_id = $1 AND status IN ('QUEUED', 'RUNNING'))::boolean
`

func (q *Queries) PendingRunExists(ctx context.Context, recordingID string) (bool, error) {
	row := q.db.QueryRow(ctx, pendingRunExists, recordingID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const readyRecordings = `-- name: ReadyRecordings :many
WITH candidates AS (
    SELECT r.experiment_id, r.test_id, r.id AS recording_id, a.id AS source_asset_id, a.generation AS source_generation,
           a.crc32c AS source_crc32c, r.clip_start_us, r.clip_end_us, t.paradigm_key, t.paradigm_version,
           t.environment_revision_id, t.protocol_version_id, e.apparatus, s.session, r.created_at,
           coalesce(ec.calibration_id::text, '')::text AS calibration_id, coalesce(ec.source, '')::text AS calibration_source
    FROM misko.test_recordings r
    JOIN misko.effective_calibrations ec ON ec.recording_id = r.id
    JOIN misko.video_assets a ON a.id = r.video_asset_id
    JOIN misko.tests t ON t.id = r.test_id
    JOIN misko.environment_revisions e ON e.id = t.environment_revision_id
    JOIN misko.protocol_steps s ON s.protocol_version_id = t.protocol_version_id AND s.position = t.step_position
    WHERE a.status = 'VERIFIED' AND t.status <> 'CANCELLED'
      AND EXISTS (SELECT 1 FROM misko.worker_capabilities wc JOIN misko.analysis_workers w ON w.id = wc.worker_id
                  WHERE w.disabled_at IS NULL AND wc.paradigm_key = t.paradigm_key AND wc.paradigm_version = t.paradigm_version)
)
SELECT c.experiment_id, c.test_id, c.recording_id, c.source_asset_id, c.source_generation::bigint AS source_generation,
       c.source_crc32c, c.clip_start_us, c.clip_end_us, c.paradigm_key, c.paradigm_version, c.environment_revision_id,
       c.protocol_version_id, c.apparatus, c.session, c.calibration_id
FROM candidates c
WHERE NOT EXISTS (
    SELECT 1 FROM misko.analysis_runs x
    WHERE x.trigger = 'AUTOMATIC' AND x.recording_id = c.recording_id AND x.source_generation = c.source_generation
      AND x.paradigm_key = c.paradigm_key AND x.paradigm_version = c.paradigm_version
      AND (c.calibration_source = 'ENVIRONMENT' OR coalesce(x.calibration_id::text, '') IN (c.calibration_id, '')))
ORDER BY c.created_at, c.recording_id
LIMIT 500
`

type ReadyRecordingsRow struct {
	ExperimentID          string
	TestID                string
	RecordingID           string
	SourceAssetID         string
	SourceGeneration      int64
	SourceCrc32c          int64
	ClipStartUs           int64
	ClipEndUs             *int64
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	ProtocolVersionID     string
	Apparatus             []byte
	Session               []byte
	CalibrationID         string
}

// ReadyRecordings lists verified recordings of tests that are not cancelled,
// with an active capability and no automatic run for the current source
// generation and calibration. An environment calibration never triggers a run for
// a recording that already has an automatic run: correcting the default must not
// silently reanalyze every recording, that stays an explicit manual run.
func (q *Queries) ReadyRecordings(ctx context.Context) ([]ReadyRecordingsRow, error) {
	rows, err := q.db.Query(ctx, readyRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadyRecordingsRow
	for rows.Next() {
		var i ReadyRecordingsRow
		if err := rows.Scan(
			&i.ExperimentID,
			&i.TestID,
			&i.RecordingID,
			&i.SourceAssetID,
			&i.SourceGeneration,
			&i.SourceCrc32c,
			&i.ClipStartUs,
			&i.ClipEndUs,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.EnvironmentRevisionID,
			&i.ProtocolVersionID,
			&i.Apparatus,
			&i.Session,
			&i.CalibrationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceObject = `-- name: SourceObject :one
SELECT object_name FROM misko.video_assets WHERE id = $1
`

func (q *Queries) SourceObject(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, sourceObject, id)
	var object_name string
	err := row.Scan(&object_name)
	return object_name, err
}

const updateRun = `-- name: UpdateRun :one
UPDATE misko.analysis_runs
SET status = $1, attempt = $2, worker_id = $3, lease_expires_at = $4,
    available_at = $5, model_version = $6, failure_reason = $7,
    finished_at = $8
WHERE id = $9
RETURNING id, experiment_id, test_id, recording_id, source_asset_id, source_generation, source_crc32c, clip_start_us, clip_end_us, calibration_id, paradigm_key, paradigm_version, metric_engine_version, result_schema_version, environment_revision_id, protocol_version_id, parameters, trigger, status, attempt, max_attempts, worker_id, lease_expires_at, available_at, model_version, failure_reason, created_by, created_at, finished_at
`

type UpdateRunParams struct {
	Status         string
	Attempt        int32
	WorkerID       *string
	LeaseExpiresAt *time.Time
	AvailableAt    time.Time
	ModelVersion   *string
	FailureReason  *string
	FinishedAt     *time.Time
	ID             string
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (MiskoAnalysisRun, error) {
	row := q.db.QueryRow(ctx, updateRun,
		arg.Status,
		arg.Attempt,
		arg.WorkerID,
		arg.LeaseExpiresAt,
		arg.AvailableAt,
		arg.ModelVersion,
		arg.FailureReason,
		arg.FinishedAt,
		arg.ID,
	)
	var i MiskoAnalysisRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.TestID,
		&i.RecordingID,
		&i.SourceAssetID,
		&i.SourceGeneration,
		&i.SourceCrc32c,
		&i.ClipStartUs,
		&i.ClipEndUs,
		&i.CalibrationID,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.MetricEngineVersion,
		&i.ResultSchemaVersion,
		&i.EnvironmentRevisionID,
		&i.ProtocolVersionID,
		&i.Parameters,
		&i.Trigger,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.ModelVersion,
		&i.FailureReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const workerByToken = `-- name: WorkerByToken :one
SELECT id, name, model_version, disabled_at, created_by, created_at
FROM misko.analysis_workers
WHERE token_sha256 = $1 AND disabled_at IS NULL
`

type WorkerByTokenRow struct {
	ID           string
	Name         string
	ModelVersion string
	DisabledAt   *time.Time
	CreatedBy    string
	CreatedAt    time.Time
}

func (q *Queries) WorkerByToken(ctx context.Context, tokenSha256 []byte) (WorkerByTokenRow, error) {
	row := q.db.QueryRow(ctx, workerByToken, tokenSha256)
	var i WorkerByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModelVersion,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const workerCapabilities = `-- name: WorkerCapabilities :many
SELECT worker_id, paradigm_key, paradigm_version
FROM misko.worker_capabilities
WHERE worker_id = $1
ORDER BY paradigm_key, paradigm_version
`

func (q *Queries) WorkerCapabilities(ctx context.Context, workerID string) ([]MiskoWorkerCapability, error) {
	rows, err := q.db.Query(ctx, workerCapabilities, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoWorkerCapability
	for rows.Next() {
		var i MiskoWorkerCapability
		if err := rows.Scan(&i.WorkerID, &i.ParadigmKey, &i.ParadigmVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
