// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const countAllTests = `-- name: CountAllTests :one
SELECT count(*) FROM misko.tests
WHERE ($1::uuid IS NULL OR experiment_id = $1::uuid)
  AND ($2::uuid IS NULL OR subject_id = $2::uuid)
  AND ($3::text = '' OR status = $3::text)
  AND ($4::text = '' OR paradigm_key = $4::text)
`

type CountAllTestsParams struct {
	ExperimentID *string
	SubjectID    *string
	Status       string
	ParadigmKey  string
}

func (q *Queries) CountAllTests(ctx context.Context, arg CountAllTestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTests,
		arg.ExperimentID,
		arg.SubjectID,
		arg.Status,
		arg.ParadigmKey,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTests = `-- name: CountTests :one
SELECT count(*) FROM misko.tests
WHERE experiment_id = $1
  AND ($2::uuid IS NULL OR subject_id = $2::uuid)
  AND ($3::uuid IS NULL OR phase_id = $3::uuid)
  AND ($4::text = '' OR status = $4::text)
  AND ($5::text = '' OR paradigm_key = $5::text)
`

type CountTestsParams struct {
	ExperimentID string
	SubjectID    *string
	PhaseID      *string
	Status       string
	ParadigmKey  string
}

func (q *Queries) CountTests(ctx context.Context, arg CountTestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTests,
		arg.ExperimentID,
		arg.SubjectID,
		arg.PhaseID,
		arg.Status,
		arg.ParadigmKey,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO misko.test_comments (test_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateCommentParams struct {
	TestID   string
	AuthorID string
	Body     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (string, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TestID, arg.AuthorID, arg.Body)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createTest = `-- name: CreateTest :one
INSERT INTO misko.tests (experiment_id, enrollment_id, subject_id, phase_id, group_id, protocol_version_id, step_position, paradigm_key, paradigm_version, environment_revision_id, planned_trials, scheduled_at, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, experiment_id, enrollment_id, subject_id, phase_id, group_id, protocol_version_id, step_position, paradigm_key, paradigm_version, environment_revision_id, planned_trials, status, scheduled_at, started_at, completed_at, cancelled_at, cancel_reason, notes, created_by, created_at, updated_at
`

type CreateTestParams struct {
	ExperimentID          string
	EnrollmentID          string
	SubjectID             string
	PhaseID               *string
	GroupID               *string
	ProtocolVersionID     string
	StepPosition          int32
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	PlannedTrials         int32
	ScheduledAt           time.Time
	Notes                 *string
	CreatedBy             string
}

func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (MiskoTest, error) {
	row := q.db.QueryRow(ctx, createTest,
		arg.ExperimentID,
		arg.EnrollmentID,
		arg.SubjectID,
		arg.PhaseID,
		arg.GroupID,
		arg.ProtocolVersionID,
		arg.StepPosition,
		arg.ParadigmKey,
		arg.ParadigmVersion,
		arg.EnvironmentRevisionID,
		arg.PlannedTrials,
		arg.ScheduledAt,
		arg.Notes,
		arg.CreatedBy,
	)
	var i MiskoTest
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.EnrollmentID,
		&i.SubjectID,
		&i.PhaseID,
		&i.GroupID,
		&i.ProtocolVersionID,
		&i.StepPosition,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.EnvironmentRevisionID,
		&i.PlannedTrials,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrial = `-- name: CreateTrial :one
INSERT INTO misko.trials (test_id, number, repetition, attempt, started_at, ended_at, notes, recorded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, test_id, number, repetition, attempt, started_at, ended_at, notes, recorded_by, created_at
`

type CreateTrialParams struct {
	TestID     string
	Number     int32
	Repetition int32
	Attempt    int32
	StartedAt  time.Time
	EndedAt    *time.Time
	Notes      *string
	RecordedBy string
}

func (q *Queries) CreateTrial(ctx context.Context, arg CreateTrialParams) (MiskoTrial, error) {
	row := q.db.QueryRow(ctx, createTrial,
		arg.TestID,
		arg.Number,
		arg.Repetition,
		arg.Attempt,
		arg.StartedAt,
		arg.EndedAt,
		arg.Notes,
		arg.RecordedBy,
	)
	var i MiskoTrial
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.Number,
		&i.Repetition,
		&i.Attempt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM misko.test_comments WHERE test_id = $1 AND id = $2
`

type DeleteCommentParams struct {
	TestID string
	ID     string
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComment, arg.TestID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComment = `-- name: GetComment :one
SELECT c.id, c.test_id, c.author_id, coalesce(u.name, '')::text AS author_name, c.body, c.created_at, c.updated_at
FROM misko.test_comments c
LEFT JOIN misko.users u ON u.id = c.author_id
WHERE c.test_id = $1 AND c.id = $2
`

type GetCommentParams struct {
	TestID string
	ID     string
}

type GetCommentRow struct {
	ID         string
	TestID     string
	AuthorID   string
	AuthorName string
	Body       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, arg.TestID, arg.ID)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentRef = `-- name: GetEnrollmentRef :one
SELECT id, experiment_id, subject_id, enrolled_at
FROM misko.enrollments
WHERE experiment_id = $1 AND id = $2
`

type GetEnrollmentRefParams struct {
	ExperimentID string
	ID           string
}

type GetEnrollmentRefRow struct {
	ID           string
	ExperimentID string
	SubjectID    string
	EnrolledAt   time.Time
}

func (q *Queries) GetEnrollmentRef(ctx context.Context, arg GetEnrollmentRefParams) (GetEnrollmentRefRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentRef, arg.ExperimentID, arg.ID)
	var i GetEnrollmentRefRow
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.SubjectID,
		&i.EnrolledAt,
	)
	return i, err
}

const getProtocolStep = `-- name: GetProtocolStep :one
SELECT s.protocol_version_id, s.position, s.paradigm_key, s.paradigm_version, s.environment_revision_id, s.trials
FROM misko.protocol_steps s
JOIN misko.protocol_versions v ON v.id = s.protocol_version_id
WHERE v.experiment_id = $1 AND v.id = $2 AND s.position = $3
`

type GetProtocolStepParams struct {
	ExperimentID      string
	ProtocolVersionID string
	Position          int32
}

type GetProtocolStepRow struct {
	ProtocolVersionID     string
	Position              int32
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	Trials                int32
}

func (q *Queries) GetProtocolStep(ctx context.Context, arg GetProtocolStepParams) (GetProtocolStepRow, error) {
	row := q.db.QueryRow(ctx, getProtocolStep, arg.ExperimentID, arg.ProtocolVersionID, arg.Position)
	var i GetProtocolStepRow
	err := row.Scan(
		&i.ProtocolVersionID,
		&i.Position,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.EnvironmentRevisionID,
		&i.Trials,
	)
	return i, err
}

const getTest = `-- name: GetTest :one
SELECT id, experiment_id, enrollment_id, subject_id, phase_id, group_id, protocol_version_id, step_position, paradigm_key, paradigm_version, environment_revision_id, planned_trials, status, scheduled_at, started_at, completed_at, cancelled_at, cancel_reason, notes, created_by, created_at, updated_at FROM misko.tests WHERE id = $1
`

func (q *Queries) GetTest(ctx context.Context, id string) (MiskoTest, error) {
	row := q.db.QueryRow(ctx, getTest, id)
	var i MiskoTest
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.EnrollmentID,
		&i.SubjectID,
		&i.PhaseID,
		&i.GroupID,
		&i.ProtocolVersionID,
		&i.StepPosition,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.EnvironmentRevisionID,
		&i.PlannedTrials,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupAt = `-- name: GroupAt :one
SELECT group_id
FROM misko.group_assignments
WHERE enrollment_id = $1
  AND valid_from <= $2::timestamptz
  AND (valid_to IS NULL OR valid_to > $2::timestamptz)
`

type GroupAtParams struct {
	EnrollmentID string
	At           time.Time
}

func (q *Queries) GroupAt(ctx context.Context, arg GroupAtParams) (string, error) {
	row := q.db.QueryRow(ctx, groupAt, arg.EnrollmentID, arg.At)
	var group_id string
	err := row.Scan(&group_id)
	return group_id, err
}

const listAllTests = `-- name: ListAllTests :many
SELECT id, experiment_id, enrollment_id, subject_id, phase_id, group_id, protocol_version_id, step_position, paradigm_key, paradigm_version, environment_revision_id, planned_trials, status, scheduled_at, started_at, completed_at, cancelled_at, cancel_reason, notes, created_by, created_at, updated_at FROM misko.tests
WHERE ($1::uuid IS NULL OR experiment_id = $1::uuid)
  AND ($2::uuid IS NULL OR subject_id = $2::uuid)
  AND ($3::text = '' OR status = $3::text)
  AND ($4::text = '' OR paradigm_key = $4::text)
ORDER BY scheduled_at DESC, id
LIMIT $6 OFFSET $5
`

type ListAllTestsParams struct {
	ExperimentID *string
	SubjectID    *string
	Status       string
	ParadigmKey  string
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListAllTests(ctx context.Context, arg ListAllTestsParams) ([]MiskoTest, error) {
	rows, err := q.db.Query(ctx, listAllTests,
		arg.ExperimentID,
		arg.SubjectID,
		arg.Status,
		arg.ParadigmKey,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoTest
	for rows.Next() {
		var i MiskoTest
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.EnrollmentID,
			&i.SubjectID,
			&i.PhaseID,
			&i.GroupID,
			&i.ProtocolVersionID,
			&i.StepPosition,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.EnvironmentRevisionID,
			&i.PlannedTrials,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.test_id, c.author_id, coalesce(u.name, '')::text AS author_name, c.body, c.created_at, c.updated_at
FROM misko.test_comments c
LEFT JOIN misko.users u ON u.id = c.author_id
WHERE c.test_id = $1
ORDER BY c.created_at, c.id
`

type ListCommentsRow struct {
	ID         string
	TestID     string
	AuthorID   string
	AuthorName string
	Body       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListComments(ctx context.Context, testID string) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTests = `-- name: ListTests :many
SELECT id, experiment_id, enrollment_id, subject_id, phase_id, group_id, protocol_version_id, step_position, paradigm_key, paradigm_version, environment_revision_id, planned_trials, status, scheduled_at, started_at, completed_at, cancelled_at, cancel_reason, notes, created_by, created_at, updated_at FROM misko.tests
WHERE experiment_id = $1
  AND ($2::uuid IS NULL OR subject_id = $2::uuid)
  AND ($3::uuid IS NULL OR phase_id = $3::uuid)
  AND ($4::text = '' OR status = $4::text)
  AND ($5::text = '' OR paradigm_key = $5::text)
ORDER BY scheduled_at, id
LIMIT $7 OFFSET $6
`

type ListTestsParams struct {
	ExperimentID string
	SubjectID    *string
	PhaseID      *string
	Status       string
	ParadigmKey  string
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListTests(ctx context.Context, arg ListTestsParams) ([]MiskoTest, error) {
	rows, err := q.db.Query(ctx, listTests,
		arg.ExperimentID,
		arg.SubjectID,
		arg.PhaseID,
		arg.Status,
		arg.ParadigmKey,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoTest
	for rows.Next() {
		var i MiskoTest
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.EnrollmentID,
			&i.SubjectID,
			&i.PhaseID,
			&i.GroupID,
			&i.ProtocolVersionID,
			&i.StepPosition,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.EnvironmentRevisionID,
			&i.PlannedTrials,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrials = `-- name: ListTrials :many
SELECT id, test_id, number, repetition, attempt, started_at, ended_at, notes, recorded_by, created_at FROM misko.trials WHERE test_id = $1 ORDER BY number
`

func (q *Queries) ListTrials(ctx context.Context, testID string) ([]MiskoTrial, error) {
	rows, err := q.db.Query(ctx, listTrials, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoTrial
	for rows.Next() {
		var i MiskoTrial
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.Number,
			&i.Repetition,
			&i.Attempt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnrollmentRef = `-- name: LockEnrollmentRef :one
SELECT id, experiment_id, subject_id, enrolled_at
FROM misko.enrollments
WHERE experiment_id = $1 AND id = $2
FOR SHARE
`

type LockEnrollmentRefParams struct {
	ExperimentID string
	ID           string
}

type LockEnrollmentRefRow struct {
	ID           string
	ExperimentID string
	SubjectID    string
	EnrolledAt   time.Time
}

// LockEnrollmentRef conflicts with the FOR UPDATE lock taken when assigning groups.
func (q *Queries) LockEnrollmentRef(ctx context.Context, arg LockEnrollmentRefParams) (LockEnrollmentRefRow, error) {
	row := q.db.QueryRow(ctx, lockEnrollmentRef, arg.ExperimentID, arg.ID)
	var i LockEnrollmentRefRow
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.SubjectID,
		&i.EnrolledAt,
	)
	return i, err
}

const lockTest = `-- name: LockTest :one
SELECT id, experiment_id, enrollment_id, subject_id, phase_id, group_id, protocol_version_id, step_position, paradigm_key, paradigm_version, environment_revision_id, planned_trials, status, scheduled_at, started_at, completed_at, cancelled_at, cancel_reason, notes, created_by, created_at, updated_at FROM misko.tests WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTest(ctx context.Context, id string) (MiskoTest, error) {
	row := q.db.QueryRow(ctx, lockTest, id)
	var i MiskoTest
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.EnrollmentID,
		&i.SubjectID,
		&i.PhaseID,
		&i.GroupID,
		&i.ProtocolVersionID,
		&i.StepPosition,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.EnvironmentRevisionID,
		&i.PlannedTrials,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const phaseExists = `-- name: PhaseExists :one
SELECT EXISTS (SELECT 1 FROM misko.experiment_phases WHERE experiment_id = $1 AND id = $2)
`

type PhaseExistsParams struct {
	ExperimentID string
	ID           string
}

func (q *Queries) PhaseExists(ctx context.Context, arg PhaseExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, phaseExists, arg.ExperimentID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const protocolVersionExists = `-- name: ProtocolVersionExists :one
SELECT EXISTS (SELECT 1 FROM misko.protocol_versions WHERE experiment_id = $1 AND id = $2)
`

type ProtocolVersionExistsParams struct {
	ExperimentID string
	ID           string
}

func (q *Queries) ProtocolVersionExists(ctx context.Context, arg ProtocolVersionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, protocolVersionExists, arg.ExperimentID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateComment = `-- name: UpdateComment :execrows
UPDATE misko.test_comments SET body = $1, updated_at = now()
WHERE test_id = $2 AND id = $3
`

type UpdateCommentParams struct {
	Body   string
	TestID string
	ID     string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateComment, arg.Body, arg.TestID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTestStatus = `-- name: UpdateTestStatus :one
UPDATE misko.tests
SET status = $1,
    started_at = $2,
    completed_at = $3,
    cancelled_at = $4,
    cancel_reason = $5,
    updated_at = now()
WHERE id = $6 AND status = $7
RETURNING id, experiment_id, enrollment_id, subject_id, phase_id, group_id, protocol_version_id, step_position, paradigm_key, paradigm_version, environment_revision_id, planned_trials, status, scheduled_at, started_at, completed_at, cancelled_at, cancel_reason, notes, created_by, created_at, updated_at
`

type UpdateTestStatusParams struct {
	Status       string
	StartedAt    *time.Time
	CompletedAt  *time.Time
	CancelledAt  *time.Time
	CancelReason *string
	ID           string
	FromStatus   string
}

func (q *Queries) UpdateTestStatus(ctx context.Context, arg UpdateTestStatusParams) (MiskoTest, error) {
	row := q.db.QueryRow(ctx, updateTestStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.CancelReason,
		arg.ID,
		arg.FromStatus,
	)
	var i MiskoTest
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.EnrollmentID,
		&i.SubjectID,
		&i.PhaseID,
		&i.GroupID,
		&i.ProtocolVersionID,
		&i.StepPosition,
		&i.ParadigmKey,
		&i.ParadigmVersion,
		&i.EnvironmentRevisionID,
		&i.PlannedTrials,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
