// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const countAdministrations = `-- name: CountAdministrations :one
SELECT count(*)
FROM misko.administrations
WHERE ($1::text = '' OR subject_id::text = $1::text)
  AND ($2::text = '' OR substance_id::text = $2::text)
  AND ($3::text = '' OR experiment_id::text = $3::text)
  AND ($4::timestamptz IS NULL OR administered_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR administered_at < $5::timestamptz)
`

type CountAdministrationsParams struct {
	SubjectID    string
	SubstanceID  string
	ExperimentID string
	FromTime     *time.Time
	ToTime       *time.Time
}

func (q *Queries) CountAdministrations(ctx context.Context, arg CountAdministrationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdministrations,
		arg.SubjectID,
		arg.SubstanceID,
		arg.ExperimentID,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConditions = `-- name: CountConditions :one
SELECT count(*)
FROM misko.subject_conditions c
WHERE ($1::text = '' OR c.disease_model_id::text = $1::text)
  AND ($2::text = '' OR c.status = $2::text)
  AND (NOT $3::boolean OR NOT EXISTS (
      SELECT 1 FROM misko.subject_conditions l
      WHERE l.subject_id = c.subject_id AND l.disease_model_id = c.disease_model_id
        AND (l.observed_at, l.created_at, l.id) > (c.observed_at, c.created_at, c.id)))
`

type CountConditionsParams struct {
	DiseaseModelID string
	Status         string
	CurrentOnly    bool
}

func (q *Queries) CountConditions(ctx context.Context, arg CountConditionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConditions, arg.DiseaseModelID, arg.Status, arg.CurrentOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdministration = `-- name: CreateAdministration :one
INSERT INTO misko.administrations (experiment_id, enrollment_id, subject_id, substance_id, substance_name, plan_id, weight_measurement_id, body_milligrams, amount_micro, unit, route, administered_at, notes, recorded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, experiment_id, enrollment_id, subject_id, substance_id, substance_name, plan_id, weight_measurement_id, body_milligrams, amount_micro, unit, route, administered_at, notes, recorded_by, created_at
`

type CreateAdministrationParams struct {
	ExperimentID        string
	EnrollmentID        string
	SubjectID           string
	SubstanceID         string
	SubstanceName       string
	PlanID              *string
	WeightMeasurementID *string
	BodyMilligrams      *int64
	AmountMicro         int64
	Unit                string
	Route               string
	AdministeredAt      time.Time
	Notes               *string
	RecordedBy          string
}

func (q *Queries) CreateAdministration(ctx context.Context, arg CreateAdministrationParams) (MiskoAdministration, error) {
	row := q.db.QueryRow(ctx, createAdministration,
		arg.ExperimentID,
		arg.EnrollmentID,
		arg.SubjectID,
		arg.SubstanceID,
		arg.SubstanceName,
		arg.PlanID,
		arg.WeightMeasurementID,
		arg.BodyMilligrams,
		arg.AmountMicro,
		arg.Unit,
		arg.Route,
		arg.AdministeredAt,
		arg.Notes,
		arg.RecordedBy,
	)
	var i MiskoAdministration
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.EnrollmentID,
		&i.SubjectID,
		&i.SubstanceID,
		&i.SubstanceName,
		&i.PlanID,
		&i.WeightMeasurementID,
		&i.BodyMilligrams,
		&i.AmountMicro,
		&i.Unit,
		&i.Route,
		&i.AdministeredAt,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createCondition = `-- name: CreateCondition :one
INSERT INTO misko.subject_conditions (subject_id, disease_model_id, disease_model_name, enrollment_id, status, observed_at, notes, recorded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, subject_id, disease_model_id, disease_model_name, enrollment_id, status, observed_at, notes, recorded_by, created_at
`

type CreateConditionParams struct {
	SubjectID        string
	DiseaseModelID   string
	DiseaseModelName string
	EnrollmentID     *string
	Status           string
	ObservedAt       time.Time
	Notes            *string
	RecordedBy       string
}

func (q *Queries) CreateCondition(ctx context.Context, arg CreateConditionParams) (MiskoSubjectCondition, error) {
	row := q.db.QueryRow(ctx, createCondition,
		arg.SubjectID,
		arg.DiseaseModelID,
		arg.DiseaseModelName,
		arg.EnrollmentID,
		arg.Status,
		arg.ObservedAt,
		arg.Notes,
		arg.RecordedBy,
	)
	var i MiskoSubjectCondition
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.DiseaseModelID,
		&i.DiseaseModelName,
		&i.EnrollmentID,
		&i.Status,
		&i.ObservedAt,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createDiseaseModel = `-- name: CreateDiseaseModel :one
INSERT INTO misko.disease_models (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateDiseaseModelParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateDiseaseModel(ctx context.Context, arg CreateDiseaseModelParams) (MiskoDiseaseModel, error) {
	row := q.db.QueryRow(ctx, createDiseaseModel, arg.Name, arg.Description)
	var i MiskoDiseaseModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO misko.intervention_plans (experiment_id, group_id, phase_id, substance_id, amount_micro, unit, route, schedule, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, experiment_id, group_id, phase_id, substance_id, amount_micro, unit, route, schedule, notes, created_at, updated_at
`

type CreatePlanParams struct {
	ExperimentID string
	GroupID      string
	PhaseID      *string
	SubstanceID  string
	AmountMicro  int64
	Unit         string
	Route        string
	Schedule     string
	Notes        *string
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (MiskoInterventionPlan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ExperimentID,
		arg.GroupID,
		arg.PhaseID,
		arg.SubstanceID,
		arg.AmountMicro,
		arg.Unit,
		arg.Route,
		arg.Schedule,
		arg.Notes,
	)
	var i MiskoInterventionPlan
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.GroupID,
		&i.PhaseID,
		&i.SubstanceID,
		&i.AmountMicro,
		&i.Unit,
		&i.Route,
		&i.Schedule,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubstance = `-- name: CreateSubstance :one
INSERT INTO misko.substances (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateSubstanceParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateSubstance(ctx context.Context, arg CreateSubstanceParams) (MiskoSubstance, error) {
	row := q.db.QueryRow(ctx, createSubstance, arg.Name, arg.Description)
	var i MiskoSubstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWeight = `-- name: CreateWeight :one
INSERT INTO misko.weight_measurements (subject_id, body_milligrams, measured_at, recorded_by)
VALUES ($1, $2, $3, $4)
RETURNING id, subject_id, body_milligrams, measured_at, recorded_by, created_at
`

type CreateWeightParams struct {
	SubjectID      string
	BodyMilligrams int64
	MeasuredAt     time.Time
	RecordedBy     string
}

func (q *Queries) CreateWeight(ctx context.Context, arg CreateWeightParams) (MiskoWeightMeasurement, error) {
	row := q.db.QueryRow(ctx, createWeight,
		arg.SubjectID,
		arg.BodyMilligrams,
		arg.MeasuredAt,
		arg.RecordedBy,
	)
	var i MiskoWeightMeasurement
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.BodyMilligrams,
		&i.MeasuredAt,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDiseaseModel = `-- name: GetDiseaseModel :one
SELECT id, name, description, created_at, updated_at
FROM misko.disease_models
WHERE id = $1
`

func (q *Queries) GetDiseaseModel(ctx context.Context, id string) (MiskoDiseaseModel, error) {
	row := q.db.QueryRow(ctx, getDiseaseModel, id)
	var i MiskoDiseaseModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentRef = `-- name: GetEnrollmentRef :one
SELECT id, experiment_id, subject_id, enrolled_at
FROM misko.enrollments
WHERE experiment_id = $1 AND id = $2
`

type GetEnrollmentRefParams struct {
	ExperimentID string
	ID           string
}

type GetEnrollmentRefRow struct {
	ID           string
	ExperimentID string
	SubjectID    string
	EnrolledAt   time.Time
}

// Reads enrollment and assignment rows to validate records; the foreign keys
// on administrations and conditions enforce the same references.
func (q *Queries) GetEnrollmentRef(ctx context.Context, arg GetEnrollmentRefParams) (GetEnrollmentRefRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentRef, arg.ExperimentID, arg.ID)
	var i GetEnrollmentRefRow
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.SubjectID,
		&i.EnrolledAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, experiment_id, group_id, phase_id, substance_id, amount_micro, unit, route, schedule, notes, created_at, updated_at
FROM misko.intervention_plans
WHERE experiment_id = $1 AND id = $2
`

type GetPlanParams struct {
	ExperimentID string
	ID           string
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (MiskoInterventionPlan, error) {
	row := q.db.QueryRow(ctx, getPlan, arg.ExperimentID, arg.ID)
	var i MiskoInterventionPlan
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.GroupID,
		&i.PhaseID,
		&i.SubstanceID,
		&i.AmountMicro,
		&i.Unit,
		&i.Route,
		&i.Schedule,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubstance = `-- name: GetSubstance :one
SELECT id, name, description, created_at, updated_at
FROM misko.substances
WHERE id = $1
`

func (q *Queries) GetSubstance(ctx context.Context, id string) (MiskoSubstance, error) {
	row := q.db.QueryRow(ctx, getSubstance, id)
	var i MiskoSubstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeight = `-- name: GetWeight :one
SELECT id, subject_id, body_milligrams, measured_at, recorded_by, created_at
FROM misko.weight_measurements
WHERE id = $1
`

func (q *Queries) GetWeight(ctx context.Context, id string) (MiskoWeightMeasurement, error) {
	row := q.db.QueryRow(ctx, getWeight, id)
	var i MiskoWeightMeasurement
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.BodyMilligrams,
		&i.MeasuredAt,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const groupAt = `-- name: GroupAt :one
SELECT group_id
FROM misko.group_assignments
WHERE enrollment_id = $1
  AND valid_from <= $2::timestamptz
  AND (valid_to IS NULL OR valid_to > $2::timestamptz)
`

type GroupAtParams struct {
	EnrollmentID string
	At           time.Time
}

func (q *Queries) GroupAt(ctx context.Context, arg GroupAtParams) (string, error) {
	row := q.db.QueryRow(ctx, groupAt, arg.EnrollmentID, arg.At)
	var group_id string
	err := row.Scan(&group_id)
	return group_id, err
}

const listAdministrations = `-- name: ListAdministrations :many
SELECT id, experiment_id, enrollment_id, subject_id, substance_id, substance_name, plan_id, weight_measurement_id, body_milligrams, amount_micro, unit, route, administered_at, notes, recorded_by, created_at
FROM misko.administrations
WHERE ($1::text = '' OR subject_id::text = $1::text)
  AND ($2::text = '' OR substance_id::text = $2::text)
  AND ($3::text = '' OR experiment_id::text = $3::text)
  AND ($4::timestamptz IS NULL OR administered_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR administered_at < $5::timestamptz)
ORDER BY administered_at DESC, id DESC
LIMIT $7::integer OFFSET $6::integer
`

type ListAdministrationsParams struct {
	SubjectID    string
	SubstanceID  string
	ExperimentID string
	FromTime     *time.Time
	ToTime       *time.Time
	PageOffset   int32
	PageLimit    int32
}

// to_time is exclusive.
func (q *Queries) ListAdministrations(ctx context.Context, arg ListAdministrationsParams) ([]MiskoAdministration, error) {
	rows, err := q.db.Query(ctx, listAdministrations,
		arg.SubjectID,
		arg.SubstanceID,
		arg.ExperimentID,
		arg.FromTime,
		arg.ToTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoAdministration
	for rows.Next() {
		var i MiskoAdministration
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.EnrollmentID,
			&i.SubjectID,
			&i.SubstanceID,
			&i.SubstanceName,
			&i.PlanID,
			&i.WeightMeasurementID,
			&i.BodyMilligrams,
			&i.AmountMicro,
			&i.Unit,
			&i.Route,
			&i.AdministeredAt,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConditions = `-- name: ListConditions :many
SELECT c.id, c.subject_id, c.disease_model_id, c.disease_model_name, c.enrollment_id, c.status, c.observed_at, c.notes, c.recorded_by, c.created_at
FROM misko.subject_conditions c
WHERE ($1::text = '' OR c.disease_model_id::text = $1::text)
  AND ($2::text = '' OR c.status = $2::text)
  AND (NOT $3::boolean OR NOT EXISTS (
      SELECT 1 FROM misko.subject_conditions l
      WHERE l.subject_id = c.subject_id AND l.disease_model_id = c.disease_model_id
        AND (l.observed_at, l.created_at, l.id) > (c.observed_at, c.created_at, c.id)))
ORDER BY c.observed_at DESC, c.created_at DESC, c.id DESC
LIMIT $5::integer OFFSET $4::integer
`

type ListConditionsParams struct {
	DiseaseModelID string
	Status         string
	CurrentOnly    bool
	PageOffset     int32
	PageLimit      int32
}

// current_only keeps the latest observation per subject and disease model,
// ordered by observation time, then recording time, then id.
func (q *Queries) ListConditions(ctx context.Context, arg ListConditionsParams) ([]MiskoSubjectCondition, error) {
	rows, err := q.db.Query(ctx, listConditions,
		arg.DiseaseModelID,
		arg.Status,
		arg.CurrentOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoSubjectCondition
	for rows.Next() {
		var i MiskoSubjectCondition
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.DiseaseModelID,
			&i.DiseaseModelName,
			&i.EnrollmentID,
			&i.Status,
			&i.ObservedAt,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiseaseModels = `-- name: ListDiseaseModels :many
SELECT id, name, description, created_at, updated_at
FROM misko.disease_models
ORDER BY lower(name), id
`

func (q *Queries) ListDiseaseModels(ctx context.Context) ([]MiskoDiseaseModel, error) {
	rows, err := q.db.Query(ctx, listDiseaseModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoDiseaseModel
	for rows.Next() {
		var i MiskoDiseaseModel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, experiment_id, group_id, phase_id, substance_id, amount_micro, unit, route, schedule, notes, created_at, updated_at
FROM misko.intervention_plans
WHERE experiment_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPlans(ctx context.Context, experimentID string) ([]MiskoInterventionPlan, error) {
	rows, err := q.db.Query(ctx, listPlans, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoInterventionPlan
	for rows.Next() {
		var i MiskoInterventionPlan
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.GroupID,
			&i.PhaseID,
			&i.SubstanceID,
			&i.AmountMicro,
			&i.Unit,
			&i.Route,
			&i.Schedule,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectConditions = `-- name: ListSubjectConditions :many
SELECT id, subject_id, disease_model_id, disease_model_name, enrollment_id, status, observed_at, notes, recorded_by, created_at
FROM misko.subject_conditions
WHERE subject_id = $1
  AND ($2::text = '' OR disease_model_id::text = $2::text)
ORDER BY observed_at DESC, created_at DESC, id DESC
`

type ListSubjectConditionsParams struct {
	SubjectID      string
	DiseaseModelID string
}

func (q *Queries) ListSubjectConditions(ctx context.Context, arg ListSubjectConditionsParams) ([]MiskoSubjectCondition, error) {
	rows, err := q.db.Query(ctx, listSubjectConditions, arg.SubjectID, arg.DiseaseModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoSubjectCondition
	for rows.Next() {
		var i MiskoSubjectCondition
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.DiseaseModelID,
			&i.DiseaseModelName,
			&i.EnrollmentID,
			&i.Status,
			&i.ObservedAt,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubstances = `-- name: ListSubstances :many
SELECT id, name, description, created_at, updated_at
FROM misko.substances
ORDER BY lower(name), id
`

func (q *Queries) ListSubstances(ctx context.Context) ([]MiskoSubstance, error) {
	rows, err := q.db.Query(ctx, listSubstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoSubstance
	for rows.Next() {
		var i MiskoSubstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeights = `-- name: ListWeights :many
SELECT id, subject_id, body_milligrams, measured_at, recorded_by, created_at
FROM misko.weight_measurements
WHERE subject_id = $1
ORDER BY measured_at DESC, id DESC
`

func (q *Queries) ListWeights(ctx context.Context, subjectID string) ([]MiskoWeightMeasurement, error) {
	rows, err := q.db.Query(ctx, listWeights, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoWeightMeasurement
	for rows.Next() {
		var i MiskoWeightMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.BodyMilligrams,
			&i.MeasuredAt,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiseaseModel = `-- name: UpdateDiseaseModel :one
UPDATE misko.disease_models
SET name = coalesce($1, name),
    description = CASE WHEN $2::text IS NULL THEN description ELSE NULLIF($2::text, '') END,
    updated_at = now()
WHERE id = $3
RETURNING id, name, description, created_at, updated_at
`

type UpdateDiseaseModelParams struct {
	Name        *string
	Description *string
	ID          string
}

func (q *Queries) UpdateDiseaseModel(ctx context.Context, arg UpdateDiseaseModelParams) (MiskoDiseaseModel, error) {
	row := q.db.QueryRow(ctx, updateDiseaseModel, arg.Name, arg.Description, arg.ID)
	var i MiskoDiseaseModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE misko.intervention_plans
SET amount_micro = coalesce($1, amount_micro),
    unit = coalesce($2, unit),
    route = coalesce($3, route),
    schedule = coalesce($4, schedule),
    notes = CASE WHEN $5::text IS NULL THEN notes ELSE NULLIF($5::text, '') END,
    updated_at = now()
WHERE experiment_id = $6 AND id = $7
RETURNING id, experiment_id, group_id, phase_id, substance_id, amount_micro, unit, route, schedule, notes, created_at, updated_at
`

type UpdatePlanParams struct {
	AmountMicro  *int64
	Unit         *string
	Route        *string
	Schedule     *string
	Notes        *string
	ExperimentID string
	ID           string
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (MiskoInterventionPlan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.AmountMicro,
		arg.Unit,
		arg.Route,
		arg.Schedule,
		arg.Notes,
		arg.ExperimentID,
		arg.ID,
	)
	var i MiskoInterventionPlan
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.GroupID,
		&i.PhaseID,
		&i.SubstanceID,
		&i.AmountMicro,
		&i.Unit,
		&i.Route,
		&i.Schedule,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubstance = `-- name: UpdateSubstance :one
UPDATE misko.substances
SET name = coalesce($1, name),
    description = CASE WHEN $2::text IS NULL THEN description ELSE NULLIF($2::text, '') END,
    updated_at = now()
WHERE id = $3
RETURNING id, name, description, created_at, updated_at
`

type UpdateSubstanceParams struct {
	Name        *string
	Description *string
	ID          string
}

func (q *Queries) UpdateSubstance(ctx context.Context, arg UpdateSubstanceParams) (MiskoSubstance, error) {
	row := q.db.QueryRow(ctx, updateSubstance, arg.Name, arg.Description, arg.ID)
	var i MiskoSubstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
