// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MiskoAdministration struct {
	ID                  string
	ExperimentID        string
	EnrollmentID        string
	SubjectID           string
	SubstanceID         string
	SubstanceName       string
	PlanID              pgtype.UUID
	WeightMeasurementID pgtype.UUID
	BodyMilligrams      *int64
	AmountMicro         int64
	Unit                string
	Route               string
	AdministeredAt      time.Time
	Notes               *string
	RecordedBy          string
	CreatedAt           time.Time
}

type MiskoDiseaseModel struct {
	ID          string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MiskoEnrollment struct {
	ID           string
	ExperimentID string
	SubjectID    string
	EnrolledAt   time.Time
	CreatedAt    time.Time
}

type MiskoEnvironment struct {
	ID          string
	Name        string
	ParadigmKey string
	Notes       *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MiskoEnvironmentRevision struct {
	ID              string
	EnvironmentID   string
	ParadigmKey     string
	Number          int32
	ParadigmVersion int32
	Apparatus       []byte
	Notes           *string
	CreatedBy       string
	CreatedAt       time.Time
}

type MiskoExperiment struct {
	ID              string
	Code            string
	Title           string
	Description     *string
	RequiresControl bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MiskoExperimentGroup struct {
	ID           string
	ExperimentID string
	Name         string
	Role         string
	TargetSize   *int32
	Description  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoExperimentPhase struct {
	ID           string
	ExperimentID string
	Name         string
	Position     int32
	Description  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoGroupAssignment struct {
	ID           string
	ExperimentID string
	EnrollmentID string
	GroupID      string
	ValidFrom    time.Time
	ValidTo      pgtype.Timestamptz
	CreatedAt    time.Time
}

type MiskoInterventionPlan struct {
	ID           string
	ExperimentID string
	GroupID      string
	PhaseID      pgtype.UUID
	SubstanceID  string
	AmountMicro  int64
	Unit         string
	Route        string
	Schedule     string
	Notes        *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoLaboratory struct {
	Singleton bool
	Name      string
	Code      *string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MiskoProtocol struct {
	ID           string
	ExperimentID string
	Name         string
	Description  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MiskoProtocolStep struct {
	ProtocolVersionID     string
	Position              int32
	ParadigmKey           string
	ParadigmVersion       int32
	EnvironmentRevisionID string
	TrialType             string
	Trials                int32
	InterTrialIntervalS   int32
	Session               []byte
	Notes                 *string
}

type MiskoProtocolVersion struct {
	ID           string
	ExperimentID string
	ProtocolID   string
	Number       int32
	StepCount    int32
	Notes        *string
	CreatedBy    string
	CreatedAt    time.Time
}

type MiskoSubject struct {
	ID        string
	Code      string
	Species   string
	Sex       string
	Strain    *string
	BirthDate pgtype.Date
	Notes     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MiskoSubjectCondition struct {
	ID               string
	SubjectID        string
	DiseaseModelID   string
	DiseaseModelName string
	EnrollmentID     pgtype.UUID
	Status           string
	ObservedAt       time.Time
	Notes            *string
	RecordedBy       string
	CreatedAt        time.Time
}

type MiskoSubstance struct {
	ID          string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MiskoUser struct {
	ID             string
	Email          string
	Name           string
	Role           string
	PasswordHash   string
	SessionVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MiskoWeightMeasurement struct {
	ID             string
	SubjectID      string
	BodyMilligrams int64
	MeasuredAt     time.Time
	RecordedBy     string
	CreatedAt      time.Time
}
