// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO misko.environments (name, paradigm_key, notes)
VALUES ($1, $2, $3)
RETURNING id, name, paradigm_key, notes, created_at, updated_at
`

type CreateEnvironmentParams struct {
	Name        string
	ParadigmKey string
	Notes       *string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (MiskoEnvironment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.Name, arg.ParadigmKey, arg.Notes)
	var i MiskoEnvironment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParadigmKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :one
INSERT INTO misko.environment_revisions (environment_id, paradigm_key, number, paradigm_version, apparatus, notes, created_by)
SELECT $1::uuid, $2::text, coalesce(max(r.number), 0) + 1, $3::integer, $4::jsonb, $5::text, $6::uuid
FROM misko.environment_revisions r
WHERE r.environment_id = $1::uuid
RETURNING id, environment_id, paradigm_key, number, paradigm_version, apparatus, notes, created_by, created_at
`

type CreateRevisionParams struct {
	EnvironmentID   string
	ParadigmKey     string
	ParadigmVersion int32
	Apparatus       []byte
	Notes           *string
	CreatedBy       string
}

// CreateRevision numbers revisions per environment; callers lock the
// environment first so concurrent revisions do not collide.
func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (MiskoEnvironmentRevision, error) {
	row := q.db.QueryRow(ctx, createRevision,
		arg.EnvironmentID,
		arg.ParadigmKey,
		arg.ParadigmVersion,
		arg.Apparatus,
		arg.Notes,
		arg.CreatedBy,
	)
	var i MiskoEnvironmentRevision
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ParadigmKey,
		&i.Number,
		&i.ParadigmVersion,
		&i.Apparatus,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT e.id, e.name, e.paradigm_key, e.notes, e.created_at, e.updated_at,
       coalesce((SELECT max(r.number) FROM misko.environment_revisions r WHERE r.environment_id = e.id), 0)::integer AS latest_revision
FROM misko.environments e
WHERE e.id = $1
`

type GetEnvironmentRow struct {
	ID             string
	Name           string
	ParadigmKey    string
	Notes          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LatestRevision int32
}

func (q *Queries) GetEnvironment(ctx context.Context, id string) (GetEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i GetEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParadigmKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestRevision,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, environment_id, paradigm_key, number, paradigm_version, apparatus, notes, created_by, created_at
FROM misko.environment_revisions
WHERE environment_id = $1 AND number = $2
`

type GetRevisionParams struct {
	EnvironmentID string
	Number        int32
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (MiskoEnvironmentRevision, error) {
	row := q.db.QueryRow(ctx, getRevision, arg.EnvironmentID, arg.Number)
	var i MiskoEnvironmentRevision
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ParadigmKey,
		&i.Number,
		&i.ParadigmVersion,
		&i.Apparatus,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRevisions = `-- name: ListAllRevisions :many
SELECT r.id, r.environment_id, e.name AS environment_name, r.paradigm_key, r.number, r.paradigm_version
FROM misko.environment_revisions r
JOIN misko.environments e ON e.id = r.environment_id
ORDER BY lower(e.name), e.id, r.number
`

type ListAllRevisionsRow struct {
	ID              string
	EnvironmentID   string
	EnvironmentName string
	ParadigmKey     string
	Number          int32
	ParadigmVersion int32
}

// Every revision with the name of its environment, so a screen can say which
// apparatus a revision id belongs to with one request.
func (q *Queries) ListAllRevisions(ctx context.Context) ([]ListAllRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listAllRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRevisionsRow
	for rows.Next() {
		var i ListAllRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.ParadigmKey,
			&i.Number,
			&i.ParadigmVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT e.id, e.name, e.paradigm_key, e.notes, e.created_at, e.updated_at,
       coalesce((SELECT max(r.number) FROM misko.environment_revisions r WHERE r.environment_id = e.id), 0)::integer AS latest_revision
FROM misko.environments e
WHERE $1::text = '' OR e.paradigm_key = $1::text
ORDER BY lower(e.name), e.id
`

type ListEnvironmentsRow struct {
	ID             string
	Name           string
	ParadigmKey    string
	Notes          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LatestRevision int32
}

func (q *Queries) ListEnvironments(ctx context.Context, paradigmKey string) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments, paradigmKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvironmentsRow
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParadigmKey,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, environment_id, paradigm_key, number, paradigm_version, apparatus, notes, created_by, created_at
FROM misko.environment_revisions
WHERE environment_id = $1
ORDER BY number
`

func (q *Queries) ListRevisions(ctx context.Context, environmentID string) ([]MiskoEnvironmentRevision, error) {
	rows, err := q.db.Query(ctx, listRevisions, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoEnvironmentRevision
	for rows.Next() {
		var i MiskoEnvironmentRevision
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ParadigmKey,
			&i.Number,
			&i.ParadigmVersion,
			&i.Apparatus,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnvironment = `-- name: LockEnvironment :one
SELECT id, name, paradigm_key, notes, created_at, updated_at
FROM misko.environments
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockEnvironment(ctx context.Context, id string) (MiskoEnvironment, error) {
	row := q.db.QueryRow(ctx, lockEnvironment, id)
	var i MiskoEnvironment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParadigmKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE misko.environments AS e
SET name = coalesce($1, e.name),
    notes = CASE WHEN $2::text IS NULL THEN e.notes ELSE NULLIF($2::text, '') END,
    updated_at = now()
WHERE e.id = $3
RETURNING e.id, e.name, e.paradigm_key, e.notes, e.created_at, e.updated_at,
          coalesce((SELECT max(r.number) FROM misko.environment_revisions r WHERE r.environment_id = e.id), 0)::integer AS latest_revision
`

type UpdateEnvironmentParams struct {
	Name  *string
	Notes *string
	ID    string
}

type UpdateEnvironmentRow struct {
	ID             string
	Name           string
	ParadigmKey    string
	Notes          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LatestRevision int32
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (UpdateEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, updateEnvironment, arg.Name, arg.Notes, arg.ID)
	var i UpdateEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParadigmKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestRevision,
	)
	return i, err
}
