// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const analysisStatusCounts = `-- name: AnalysisStatusCounts :many
SELECT status, count(*) AS total FROM misko.analysis_runs
WHERE status IN ('QUEUED', 'RUNNING', 'FAILED')
GROUP BY status
`

type AnalysisStatusCountsRow struct {
	Status string
	Total  int64
}

func (q *Queries) AnalysisStatusCounts(ctx context.Context) ([]AnalysisStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, analysisStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalysisStatusCountsRow
	for rows.Next() {
		var i AnalysisStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentSucceededRuns = `-- name: RecentSucceededRuns :many
SELECT r.id, r.finished_at, r.paradigm_key, r.paradigm_version, s.code AS subject_code, e.code AS experiment_code, t.id AS test_id
FROM misko.analysis_runs r
JOIN misko.tests t ON t.id = r.test_id
JOIN misko.subjects s ON s.id = t.subject_id
JOIN misko.experiments e ON e.id = t.experiment_id
WHERE r.status = 'SUCCEEDED'
ORDER BY r.finished_at DESC, r.id DESC
LIMIT $1::integer
`

type RecentSucceededRunsRow struct {
	ID              string
	FinishedAt      *time.Time
	ParadigmKey     string
	ParadigmVersion int32
	SubjectCode     string
	ExperimentCode  string
	TestID          string
}

func (q *Queries) RecentSucceededRuns(ctx context.Context, rowLimit int32) ([]RecentSucceededRunsRow, error) {
	rows, err := q.db.Query(ctx, recentSucceededRuns, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentSucceededRunsRow
	for rows.Next() {
		var i RecentSucceededRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.FinishedAt,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.SubjectCode,
			&i.ExperimentCode,
			&i.TestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordingsAwaitingCalibrationCheck = `-- name: RecordingsAwaitingCalibrationCheck :many
WITH latest_calibration AS (
    SELECT c.recording_id, c.status
    FROM misko.calibrations c
    WHERE NOT EXISTS (SELECT 1 FROM misko.calibrations n WHERE n.supersedes_id = c.id)
)
SELECT r.id AS recording_id, t.paradigm_key, t.paradigm_version, er.apparatus
FROM misko.test_recordings r
JOIN misko.video_assets a ON a.id = r.video_asset_id
JOIN misko.tests t ON t.id = r.test_id
JOIN misko.environment_revisions er ON er.id = t.environment_revision_id
LEFT JOIN latest_calibration lc ON lc.recording_id = r.id
WHERE a.status = 'VERIFIED' AND (lc.status IS NULL OR lc.status <> 'VALID')
`

type RecordingsAwaitingCalibrationCheckRow struct {
	RecordingID     string
	ParadigmKey     string
	ParadigmVersion int32
	Apparatus       []byte
}

// Every verified recording whose calibration chain has no unsuperseded VALID
// entry. Whether the paradigm actually requires calibration for it is a rule
// of the paradigm catalog, not of the database, so it is decided in Go from
// this candidate set (mirrors the single-recording calibration status check).
func (q *Queries) RecordingsAwaitingCalibrationCheck(ctx context.Context) ([]RecordingsAwaitingCalibrationCheckRow, error) {
	rows, err := q.db.Query(ctx, recordingsAwaitingCalibrationCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingsAwaitingCalibrationCheckRow
	for rows.Next() {
		var i RecordingsAwaitingCalibrationCheckRow
		if err := rows.Scan(
			&i.RecordingID,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.Apparatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testStatusCounts = `-- name: TestStatusCounts :many

SELECT status, count(*) AS total FROM misko.tests GROUP BY status
`

type TestStatusCountsRow struct {
	Status string
	Total  int64
}

// Read-only aggregation across the tests, analysis and calibration domains,
// same standing as the reports package: these queries never write.
func (q *Queries) TestStatusCounts(ctx context.Context) ([]TestStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, testStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestStatusCountsRow
	for rows.Next() {
		var i TestStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upcomingTests = `-- name: UpcomingTests :many
SELECT t.id, t.scheduled_at, t.paradigm_key, t.paradigm_version, s.code AS subject_code, e.code AS experiment_code
FROM misko.tests t
JOIN misko.subjects s ON s.id = t.subject_id
JOIN misko.experiments e ON e.id = t.experiment_id
WHERE t.status = 'PLANNED'
ORDER BY t.scheduled_at ASC, t.id
LIMIT $1::integer
`

type UpcomingTestsRow struct {
	ID              string
	ScheduledAt     time.Time
	ParadigmKey     string
	ParadigmVersion int32
	SubjectCode     string
	ExperimentCode  string
}

func (q *Queries) UpcomingTests(ctx context.Context, rowLimit int32) ([]UpcomingTestsRow, error) {
	rows, err := q.db.Query(ctx, upcomingTests, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpcomingTestsRow
	for rows.Next() {
		var i UpcomingTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledAt,
			&i.ParadigmKey,
			&i.ParadigmVersion,
			&i.SubjectCode,
			&i.ExperimentCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
