// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubjects = `-- name: CountSubjects :one
SELECT count(*)
FROM misko.subjects
WHERE ($1::text = '' OR code ILIKE '%' || $1::text || '%' ESCAPE '\' OR strain ILIKE '%' || $1::text || '%' ESCAPE '\')
  AND ($2::text = '' OR species = $2::text)
  AND ($3::text = '' OR sex = $3::text)
`

type CountSubjectsParams struct {
	Search  string
	Species string
	Sex     string
}

func (q *Queries) CountSubjects(ctx context.Context, arg CountSubjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubjects, arg.Search, arg.Species, arg.Sex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO misko.subjects (code, species, sex, strain, birth_date, notes)
VALUES ($1, $2, $3, $4, $5::date, $6)
RETURNING id, code, species, sex, strain, birth_date, notes, created_at, updated_at
`

type CreateSubjectParams struct {
	Code      string
	Species   string
	Sex       string
	Strain    *string
	BirthDate pgtype.Date
	Notes     *string
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (MiskoSubject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.Code,
		arg.Species,
		arg.Sex,
		arg.Strain,
		arg.BirthDate,
		arg.Notes,
	)
	var i MiskoSubject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Species,
		&i.Sex,
		&i.Strain,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :execrows
DELETE FROM misko.subjects
WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubject = `-- name: GetSubject :one
SELECT id, code, species, sex, strain, birth_date, notes, created_at, updated_at
FROM misko.subjects
WHERE id = $1
`

func (q *Queries) GetSubject(ctx context.Context, id string) (MiskoSubject, error) {
	row := q.db.QueryRow(ctx, getSubject, id)
	var i MiskoSubject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Species,
		&i.Sex,
		&i.Strain,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, code, species, sex, strain, birth_date, notes, created_at, updated_at
FROM misko.subjects
WHERE ($1::text = '' OR code ILIKE '%' || $1::text || '%' ESCAPE '\' OR strain ILIKE '%' || $1::text || '%' ESCAPE '\')
  AND ($2::text = '' OR species = $2::text)
  AND ($3::text = '' OR sex = $3::text)
ORDER BY
    CASE WHEN $4::text = 'code' AND NOT $5::boolean THEN lower(code) END ASC,
    CASE WHEN $4::text = 'code' AND $5::boolean THEN lower(code) END DESC,
    CASE WHEN $4::text = 'species' AND NOT $5::boolean THEN species END ASC,
    CASE WHEN $4::text = 'species' AND $5::boolean THEN species END DESC,
    CASE WHEN $4::text = 'sex' AND NOT $5::boolean THEN sex END ASC,
    CASE WHEN $4::text = 'sex' AND $5::boolean THEN sex END DESC,
    CASE WHEN $4::text = 'birthDate' AND NOT $5::boolean THEN birth_date END ASC NULLS LAST,
    CASE WHEN $4::text = 'birthDate' AND $5::boolean THEN birth_date END DESC NULLS LAST,
    CASE WHEN $4::text = 'createdAt' AND NOT $5::boolean THEN created_at END ASC,
    CASE WHEN $4::text = 'createdAt' AND $5::boolean THEN created_at END DESC,
    id ASC
LIMIT $7::integer OFFSET $6::integer
`

type ListSubjectsParams struct {
	Search     string
	Species    string
	Sex        string
	SortKey    string
	Descending bool
	PageOffset int32
	PageLimit  int32
}

// The sort key is allowlisted by the application; id breaks ties for stable paging.
func (q *Queries) ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]MiskoSubject, error) {
	rows, err := q.db.Query(ctx, listSubjects,
		arg.Search,
		arg.Species,
		arg.Sex,
		arg.SortKey,
		arg.Descending,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiskoSubject
	for rows.Next() {
		var i MiskoSubject
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Species,
			&i.Sex,
			&i.Strain,
			&i.BirthDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE misko.subjects
SET code = coalesce($1, code),
    species = coalesce($2, species),
    sex = coalesce($3, sex),
    strain = CASE WHEN $4::text IS NULL THEN strain ELSE NULLIF($4::text, '') END,
    notes = CASE WHEN $5::text IS NULL THEN notes ELSE NULLIF($5::text, '') END,
    birth_date = CASE WHEN $6::boolean THEN NULL ELSE coalesce($7::date, birth_date) END,
    updated_at = now()
WHERE id = $8
RETURNING id, code, species, sex, strain, birth_date, notes, created_at, updated_at
`

type UpdateSubjectParams struct {
	Code           *string
	Species        *string
	Sex            *string
	Strain         *string
	Notes          *string
	ClearBirthDate bool
	BirthDate      pgtype.Date
	ID             string
}

// A NULL argument leaves a column unchanged; an empty strain or notes clears it.
func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (MiskoSubject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.Code,
		arg.Species,
		arg.Sex,
		arg.Strain,
		arg.Notes,
		arg.ClearBirthDate,
		arg.BirthDate,
		arg.ID,
	)
	var i MiskoSubject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Species,
		&i.Sex,
		&i.Strain,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
